### ISSUE TITLE
Thoughts on _get_location

### ISSUE THREAD

**Issue by zulufoxtrot** [Hyundai-Kia-Connect/hyundai_kia_connect_api#129]
* Hyundai / Kia Connect version: 1.40.2
* Python version: 3.9
* Operating System: MacOS

### Description

`_get_cached_vehicle_state` calls `_get_location`.
If I understand correctly,`_get_location` triggers a connection to the car from the manufacturer's servers, to fetch the car's position.
Does it not defeat the whole point of using cached data? Especially since location data is already present in the cached response.

I see there is a "todo" comment to prevent calls when the cached data is "fresh" but even then, should the car be contacted at all when requesting cached data?

My car is parked in an underground parking. The car does appear to have cell service, I'm not sure about GPS coverage. Either way, the API call from `_get_location` returns this:
`'resCode': '4081', 'resMsg': 'Request timeout. - Request timeout.'`

The server takes 2 minutes to return this response, which I'm guessing is the timeout for the car-server API. I'm not sure if the car gets the call from the server but fails to get GPS signal, or if the call goes through at all.

**Comment by cdnninja** [comment]
Which region?   Some regions can never provide cached location, others do.  Perfect world cached vehicle state never contacts the car or only if required.

**Comment by zulufoxtrot** [comment]
Kia EU. In my case, the API appears to consistently return the last known location in the cached data response.

**Comment by zulufoxtrot** [comment]
Looking at the cached response I have right now, this PR should work. Will test and report back.

 Happy to contribute! Please bear with me, I just got this car and I'm getting used this API and its shortcomings :)

**Comment by cdnninja** [comment]
Appreciated! Bear with me as well! Note a developer by trade so often not familiar with best practices.   Just something I do in my spare time. 

https://github.com/fuatakgun/kia_uvo/tree/v2.0 being where I spend most of my time and the reason this was created.  We started to decouple the home assistant work from the API work as we saw a need for a python library that supports these cars.

**Comment by zulufoxtrot** [comment]
So, I checked today:
- when doing a forced update, no location data is present in the response. `_get_location` must be used
- when doing a cached update, location data is present (as already discussed)

About the car's "online" behavior:
- After the car is powered off, it will still respond to forced updates for some time. I'm not sure how long exactly. At least 5 minutes, at most 1 hour. I read somewhere that the bus used by the API stays powered on for 30 minutes after each call (which drains the 12v battery), so maybe 30 minutes.
- After the car stops responding, and unless the car is charging, there is no way (AFAIK) to perform forced updates until the car is turned on again. Same behavior with the Kia Connect app.
- At some point, the car pushes an update by itself. I'm not sure about the trigger. It did it today at 6AM, I had stopped interacting with it since ~5PM the day before.

**Comment by cdnninja** [comment]
This is really great info! It appears different than my ICE Canadian car but eat region and models are different.

**Comment by zulufoxtrot** [comment]
More notes:

- The timeouts I observed yesterday were most likely caused by this "offline" behiavor and not by the absence of cell/GPS coverage. It turns out the position API works just fine when the car is in my underground parking, with surprisingly good GPS accuracy, as long as the car is listening for API calls.
- More parameters might be involved in the API behavior. Maybe the car monitors the state of the 12v and stops the API service to preserve it when it drops below a certain voltage/SoC. I've heard that enough API calls could drain the 12v. Maybe Kia implemented a fix? I have a niro 2020, so the first iteration that came with UVO, but I'm on the latest infotainment update. I'm just speculating.

And there is this interesting key in the API response:

```
'remoteWaitingTimeAlert': 
    {
    'remoteControlAvailable': 1, 
    'remoteControlWaitingTime': 168, 
    'elapsedTime': '04:53:07'
    }
```

AFAIK, `remoteControlAvailable` is always `1`.
 `remoteControlWaitingTime` is always `168`. Not sure about the unit. Maybe hours. 168 / 24 = 7, so there would be a trigger once a week maybe?
`elapsedTime` indicates the time since the car was last powered off. When the car is on (contact or engine running), it is always `00:00:00`.

**Comment by zulufoxtrot** [comment]
Spent more time toying around with the API today. Put the car in utility mode to prevent any sleep.
I got somewhat consistent results for 2 hours and did force refreshes every ~2 minutes, just to see how far I could go (and monitor how fast the 12v recharged).
The API then began returning various errors: request timeout, duplicate request, proxy issues, "undefined error". Even on "simple" requests that do not involve the car, like `get_stamp`.
I thought maybe the rate limit kicked in (in a very inconsistent way). The Kia connect app still worked though and could trigger force refreshes.
Eventually the Kia connect app logged me out. Right now I'm having issues reconnecting, it fails but very inconsistently. Not sure if I'm being rate limited or if there's an outage. Will keep trying tomorrow.

**Comment by cdnninja** [comment]
I have been struggling to get this stable over here for EU: https://github.com/fuatakgun/kia_uvo/issues/424

I am wondering if for force update I update the code to make it attempt a force update and if that fails catch the failure and do a cached update instead.  It isn't ideal, not sure if that is better or not.   Thoughts?

**Comment by zulufoxtrot** [comment]
> Thoughts?

IMO, forced updates and cached updates are functionally different, with different expected outputs depending on the use case. One should not be a substitute for the other.
 
If the update fails, let it fail.

I agree we do need better API error handling, though. Want me to implement it? I've had plenty of API errors these past few days.

**Comment by cdnninja** [comment]
Yes always open to PRs.  Error handling is something we need to improve on. On Nov 21, 2022, at 10:03 AM, zulufoxtrot ***@***.***> wrote:﻿

Thoughts?

IMO, forced updates and cached updates are functionally different, with different expected outputs depending on the use case. One should not be a substitute for the other.
If the update fails, let it fail.
I agree we do need better API error handling, though. Want me to implement it? I've had plenty of API errors these past few days.

**Comment by zulufoxtrot** [comment]
Closing this, implemented in https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/131
