### ISSUE TITLE
Question on headers and tokens

### ISSUE THREAD

**Issue by zulufoxtrot** [Hyundai-Kia-Connect/hyundai_kia_connect_api#140]
* Hyundai / Kia Connect version: 1.40.10

Quick question for you @cdnninja .

I am doing some refactoring in the KiaUvoApiEU class and I am comparing headers in requests.

All authenticated requests use identical headers, except `_get_forced_vehicle_state`. It passes the refresh token (`token.refresh_token`) instead of the access token.

This API uses the Oauth2 standard, and if I understand correctly, the refresh token should only be used to get a new access token once the original access token expires.

So, unless the API does not respect the Oauth2 spec, we should pass the access token like all other requests, no? (unless of course the access token expired, but that should be handled in a separate request)

Looking at the git history, it used to be the case but was modified in early november (@jwefers).

**Comment by cdnninja** [comment]
Well this may explain some of our issues!  Great find.  I will drop a PR and make sure to comment to give you credit for this.

**Comment by zulufoxtrot** [comment]
Thanks! What surprises me is that it worked at all (at least, sometimes) while supplying the wrong token. Maybe the server handles tokens incorrectly, IDK.
I'm not sure it will solve our issues, either. The errors I usually get from the API (request timeout mostly) are not consistent with a token/authorization problem.
Anyway, I tested a force refresh with the access token instead of the refresh token. It works.
