### ISSUE TITLE
Android Bluelink App language is reset to English when using hyundai_kia_connect_api

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#145]
* Hyundai / Kia Connect version: v1.40.11
* Python version: 3.9.13
* Operating System: Windows 10 and Raspberry Pi 11 (bullseye)
* Android Bluelink App: 2.0.7
 
### Description
When the Android Bluelink App language is configured for non-English, by using the hyundai_kia_connect_api the Android Bluelink App is reset to English. So somehow the authentication/login/api does reset the Android Bluelink App to English.

### What I Did

I've looked at the source code of hyundai_kia_connect_api and I thought it's the side effect of the following python statement in KiaUvoApiEU.py, line 68:
```
        if BRANDS[brand] == BRAND_KIA:
            auth_client_id = "f4d531c7-1043-444d-b09a-ad24bd913dd4"
            self.LOGIN_FORM_URL: str = (
                "https://"
                + self.LOGIN_FORM_HOST
                + "/auth/realms/eukiaidm/protocol/openid-connect/auth?client_id="
                + auth_client_id
                + "&scope=openid%20profile%20email%20phone&response_type=code&hkid_session_reset=true&redirect_uri="
                + self.USER_API_URL
                + "integration/redirect/login&ui_locales=en&state=$service_id:$user_id"
            )
        elif BRANDS[brand] == BRAND_HYUNDAI:
            auth_client_id = "64621b96-0f0d-11ec-82a8-0242ac130003"
            self.LOGIN_FORM_URL: str = (
                "https://"
                + self.LOGIN_FORM_HOST
                + "/auth/realms/euhyundaiidm/protocol/openid-connect/auth?client_id="
                + auth_client_id
                + "&scope=openid%20profile%20email%20phone&response_type=code&hkid_session_reset=true&redirect_uri="
                + self.USER_API_URL
                + "integration/redirect/login&ui_locales=en&state=$service_id:$user_id"
            )
```

The statement "ui_locales=en" could cause the side effect? Should it be "ui_locales=de" for Germany and "ui_locales=nl" for the Netherlands? But changing that, still the language setting in the Android Bluelink App is reset to English.

**Comment by cdnninja** [comment]
Could you try editing this and seeing if it helps? https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/9a3beacd620044e8a5cd0d5d52ceb22b1f338e9b/hyundai_kia_connect_api/KiaUvoApiEU.py#L626

This line also references langauge: 
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/9a3beacd620044e8a5cd0d5d52ceb22b1f338e9b/hyundai_kia_connect_api/KiaUvoApiEU.py#L597

We have had this reported on kia_uvo too but I haven't spent time testing since I don't have a car in EU. Makes it hard to test.

**Comment by cdnninja** [comment]
Reference someone else who had this.  Not something I could focus on at the time but if you can test out and implement the languages the app supports I can extend into kia_uvo https://github.com/fuatakgun/kia_uvo/issues/339

**Comment by ZuinigeRijder** [comment]
I tried it out, the BlueLink App kept the language Dutch, when changing all above.

**Comment by cdnninja** [comment]
Awesome.   I assume the app has a few language options.  I am thinking we may this an option parameter for the vehicle manager init? If not passed we just take default of en I find it odd this isn't just set and stored to the account but this is the way.

**Comment by ZuinigeRijder** [comment]
Ok, I have tried to make the changes, see the attached patch file. 
But I was not sure if the way I included this in KiaUvoApiEU.py is the correct way to do this, namely:

```
LANGUAGE = VehicleManager.language
```

I also put the patch file in text here below, 

```
Left base folder: C:\Users\Rick\git\monitor\hyundai_kia_connect_api-1.40.11
Right base folder: C:\Users\Rick\git\monitor\hyundai_kia_connect_api
diff -r KiaUvoApiEU.py KiaUvoApiEU.py
7a8
> import VehicleManager
38a40
> LANGUAGE = VehicleManager.language
77c79
<                 + "integration/redirect/login&ui_locales=en&state=$service_id:$user_id"
---
>                 + "integration/redirect/login&ui_locales=" + LANGUAGE + "&state=$service_id:$user_id"
88c90
<                 + "integration/redirect/login&ui_locales=en&state=$service_id:$user_id"
---
>                 + "integration/redirect/login&ui_locales=" + LANGUAGE + "&state=$service_id:$user_id"
668c670
<             + "oauth2/redirect&lang=en"
---
>             + "oauth2/redirect&lang=" + LANGUAGE
697c699
<         payload = {"lang": "en"}
---
>         payload = {"lang": LANGUAGE}
diff -r VehicleManager.py VehicleManager.py
31c31
<     def __init__(self, region: int, brand: int, username: str, password: str, pin: str, geocode_api_enable: bool = False, geocode_api_use_email: bool = False):
---
>     def __init__(self, region: int, brand: int, username: str, password: str, pin: str, geocode_api_enable: bool = False, geocode_api_use_email: bool = False, language: str = "en"):
38a39
>         self.language: str = language

```
[Issue145.patch.txt](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/files/10087198/Issue145.patch.txt)

**Comment by cdnninja** [comment]
Two thoughts would be look at using enum's in the constant to define the valid options.

**Comment by ZuinigeRijder** [comment]
Actually I can select 15 languages, so an Enum is not so flexible. You just pass [the locale as a string according to the wanted language ](https://www.science.co.il/language/Locale-codes.php)is more flexible. In the patch I did add in the previous post, the default language is "en", so you just describe the possible language abbreviations in the README or as a link to a page describing the language abbreviations.

**Comment by cdnninja** [comment]
That works for me! Could you drop a PR?

**Comment by ZuinigeRijder** [comment]
Thanks for the merge, really appreciate the work @cdnninja 
The language feature is now used by my new release https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/releases/tag/R2.9.0

**Comment by cdnninja** [comment]
Thank you for this! Greatly appreciate the contribution!
