### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by povlhp** [Hyundai-Kia-Connect/hyundai_kia_connect_api#178]
Spelling error in:
[hyundai_kia_connect_api](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/tree/1d0cd00772f40486226e013c72623940e94e2407)/[hyundai_kia_connect_api](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/tree/1d0cd00772f40486226e013c72623940e94e2407/hyundai_kia_connect_api)/KiaUvoApiEU.py

Line 339, it says seat_staus instead of seat_status

```
 vehicle.rear_left_seat_staus = SEAT_STATUS[get_child_value(
            state, "vehicleStatus.seatHeaterVentState.rlSeatHeatState"
        )]
        vehicle.rear_right_seat_status = SEAT_STATUS[get_child_value(
            state, "vehicleStatus.seatHeaterVentState.rrSeatHeatState"
        )]
```

**Comment by cdnninja** [comment]
Great find.  I have created a PR here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/179

Feel free to drop PRs for items like this.  Always appreciated!
