### ISSUE TITLE
Precision of range and total driving range has too many digits.

### ISSUE THREAD

**Issue by grahamrjuk** [Hyundai-Kia-Connect/hyundai_kia_connect_api#216]
* Hyundai / Kia Connect version: 2.3.1
* Python version: 3.10
* Operating System:
** Home Assistant 2022.12.8
** Supervisor 2022.11.2
** Operating System 9.4
** Frontend 20221213.1 - latest

### Description

Precision of range and total driving range has too many digits.
For example:

IONIQ EV Total Driving Range
32 minutes ago
106.2524272 mi

### What I Did

Viewed the values in Home Assistant.
Precision is too great.

Preferably something like two decimal places (certainly no more).

**Comment by cdnninja** [comment]
Could you post the contents of your data sensor attribute? I assume the api provides this many digits?

**Comment by grahamrjuk** [comment]
Yes, this many digits are in the sensor data. I have removed the location from the data below, otherwise unedited.

Vehicle data
alt: 0
type: 0
head: 262
speed:
value: 0
unit: 0
accuracy:
hdop: 0
pdop: 0
time: '20221227184211'
vehicleStatus:
airCtrlOn: false
engine: false
doorLock: true
doorOpen:
frontLeft: 0
frontRight: 0
backLeft: 0
backRight: 0
trunkOpen: false
airTemp:
value: 02H
unit: 0
hvacTempType: 0
defrost: false
acc: false
evStatus:
batteryCharge: false
batteryStatus: 61
batteryPlugin: 0
remainTime2:
etc1:
value: 34
unit: 1
etc2:
value: 560
unit: 1
etc3:
value: 170
unit: 1
atc:
value: 170
unit: 1
drvDistance:
- rangeByFuel:
evModeRange:
value: 106.2524272
unit: 3
totalAvailableRange:
value: 106.2524272
unit: 3
type: 2
reservChargeInfos:
reservChargeInfo:
reservChargeInfoDetail:
reservInfo:
day:
- 1
time:
time: '0540'
timeSection: 0
reservChargeSet: false
reservFatcSet:
defrost: true
airTemp:
value: 0AH
unit: 0
hvacTempType: 0
airCtrl: 0
heating1: 0
offpeakPowerInfo:
offPeakPowerTime1:
starttime:
time: '1200'
timeSection: 0
endtime:
time: '1200'
timeSection: 0
offPeakPowerFlag: 0
reserveChargeInfo2:
reservChargeInfoDetail:
reservInfo:
day:
- 2
- 3
- 4
- 5
time:
time: '0740'
timeSection: 0
reservChargeSet: false
reservFatcSet:
defrost: true
airTemp:
value: 0AH
unit: 0
hvacTempType: 0
airCtrl: 0
heating1: 0
reservFlag: 0
ect:
start:
day: 9
time:
time: '1200'
timeSection: 0
end:
day: 9
time:
time: '1200'
timeSection: 0
targetSOClist:
- targetSOClevel: 80
plugType: 0
- targetSOClevel: 100
plugType: 1
ign3: false
hoodOpen: false
transCond: true
steerWheelHeat: 0
sideBackWindowHeat: 0
tirePressureLamp:
tirePressureLampAll: 0
tirePressureLampFL: 0
tirePressureLampFR: 0
tirePressureLampRL: 0
tirePressureLampRR: 0
battery:
batSoc: 81
batState: 0
sleepModeCheck: true
time: '20221227184213'
remoteWaitingTimeAlert:
remoteControlAvailable: 1
remoteControlWaitingTime: 168
elapsedTime: '00:03:39'
systemCutOffAlert: 0
tailLampStatus: 0
hazardStatus: 0
odometer:
value: 0
unit: 1
Vehicle name
IONIQ EV

**Comment by grahamrjuk** [comment]
I have changed the units to miles, from km, but even before that there were too many digits precision.

**Comment by cdnninja** [comment]
@ZuinigeRijder if I change this in the API would this impact you?  It would be easier than doing the home assistant side and not sold this level of precision is useful to anyone else who may consume the api. I wouldn't think so.

**Comment by ZuinigeRijder** [comment]
> @ZuinigeRijder if I change this in the API would this impact you? It would be easier than doing the home assistant side and not sold this level of precision is useful to anyone else who may consume the api. I wouldn't think so.

My tool will not be impacted when the precision in km is only 1 digit. However, changing from km to miles would impact my tool.

**Comment by cdnninja** [comment]
> > @ZuinigeRijder if I change this in the API would this impact you? It would be easier than doing the home assistant side and not sold this level of precision is useful to anyone else who may consume the api. I wouldn't think so.
> 
> My tool will not be impacted when the precision in km is only 1 digit. However, changing from km to miles would impact my tool.

Thanks for the quick reply.   I will start rounding these values to 2 decimal places. 

The km / miles item is a home assistant thing.   As a note for your tool I don't control units the car does.   The API however does have a _unit attribute which shows if km or miles.  In home assistant we injest that and can auto convert to a different unit based on settings.

**Comment by cdnninja** [comment]
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/221 has been merged for this.  

@grahamrjuk are you able to update in HACS by clicking redownload and select version of "master".  Let me know if everything looks okay on the rounding afterward and I can close this out.

**Comment by grahamrjuk** [comment]
Works nicely for me. Two decimal places is probably more than necessary, but much more sensible than what I had before.
I can template in Home Assistant if I want to do anything different.

**Comment by cdnninja** [comment]
What would be your ideal count? Trying to find the balance on detail. I could see has taking this down to less or no decimals.

**Comment by ZuinigeRijder** [comment]
> What would be your ideal count? Trying to find the balance on detail. I could see has taking this down to less or no decimals.

For km the odometer is sending it in 100 meters, so 1 digit. So at least 1 digit after the decimal point is needed for km. 
Examples: 
- _odometer_value=20795.4
- 'odometer': {'value': 20795.4, 'unit': 1}

**Comment by grahamrjuk** [comment]
Not sure there is an ideal. For these measurements no decimals are needed. But two decimal places is quite reasonable for distances in general. I would be happy to leave it as it is now - or go to 1 decimal place as commented above, to be consistent with other measurements.

**Comment by cdnninja** [comment]
I dropped to one considering that makes it match odometer.    Thanks for the feedback.
