### ISSUE TITLE
"last_updated_at" is not in ISO time format

### ISSUE THREAD

**Issue by Empor-co** [Hyundai-Kia-Connect/hyundai_kia_connect_api#23]
* Hyundai / Kia Connect version: 1.18.15
* Python version: 3.x
* Operating System:

### Description

Date Format is not ISO. [Python ISO Time](https://stackoverflow.com/questions/2150739/iso-time-iso-8601-in-python)

### What I Did
While forwarding the `last_updated_at` via mqtt to openHAB, I recognized that it isn't correctly parsed in openHAB.
This seems to be due to a missing "T" between date and time e.g:
`2022-01-20 09:12:34+01:00`
instead of
`2022-01-20T09:12:34+01:00`

My current workaround is to do an ingress regex `REGEX:s/\s/T/g`, which I also could do in my python script.
But wouldn't it also be possible to provide the `last_update_at` additionally in iso, e.g. as `last_updated_at_iso`?

**Comment by cdnninja** [comment]
Right now last updated is stored as a python date time format.  As per: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/293bf750496be4b24eadab02af2d84df355c95a9/hyundai_kia_connect_api/Vehicle.py#L34

I would think you can use your link to convert to ISO if that is your desired string format by using .isoformat().

**Comment by cdnninja** [comment]
@Empor-co  let me know if I can close this.

**Comment by Empor-co** [comment]
@cdnninja: I originally planned to leverage a simple list of attributes to be published via MQTT like
`pub_list = ["air_temperature", "car_battery_percentage", "ev_battery_percentage", "ev_driving_distance", "odometer",
            "name", "last_updated_at"]` where the `last_updated_at` would be nice to be ISO, but I meanwhile decided to "enhance" some of the values anyhow - like calculating the consumption between the last to updates or the change of SOC during charging.

So yes, we can close this "issue".

Thank you for your support.
