### ISSUE TITLE
date/timestamp sometimes wrong, old date/timestamp, while the longitude/latitude has been changed

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#234]
* Hyundai / Kia Connect version: v1.52.13
* Python version: 3.9.13
* Operating System: Windows 10

### Description

Sometimes the location information (latitude and longitude) is changed, but the date/time is the same as the previous date/time stamp.
It could be that this is NOT a problem of the hyundai_kia_connect_api, but a problem of the server sending the wrong date/time stamp, like it also sends the wrong odometer for my IONIQ 5 in combination with infotainment version 221129.

Example of monitor.csv, using [monitor.py](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/blob/main/monitor.py)
````
2022-12-31 16:28:19+01:00, 5.118544, ....
2022-12-31 16:28:19+01:00, 5.085289, ....
2023-01-02 16:38:09+01:00, 5.118586, ....
````

The date/time of the second line in this example is wrong, because the longitude is different, but date/timestamp not.
The date should be 2023-01-02 and the time in this case would be around 16:10. So it looks that an old date/time stamp is retrieved. 

Could there be another later date/timestamp, which should overrule the general timestamp?

### What I Did

I looked at the hyundai_kia_connect_api source code, but could not find directly something wrong there. Also another user did report the same problem, [see this post in Dutch](https://gathering.tweakers.net/forum/list_message/73993972#73993972).

Unfortunately it is difficult to find the problem, because a next run it could be correct.

**Comment by cdnninja** [comment]
Just to confirm a few things. The timestamp above is that vehicle.location? (_location_last_set_time)  If so here is where it is set: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/d2856a168ac25d5cf2e723f1e1ee86e3623c330f/hyundai_kia_connect_api/KiaUvoApiEU.py#L572-L578

Or are you using vehicle.last_updated_at?  This value is last time the car reported data back to the cloud.

**Comment by cdnninja** [comment]
I looked at your code.  Looks like you are using last updated not last gps location.  In theory would think they are the same but they aren't in the API. https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/blob/e3f016ac18c1d260e9f20f4e52d0be5d003a11f9/monitor.py#L214

**Comment by ZuinigeRijder** [comment]
Are there use cases for having those different timestamps?
However, as far as I can see the location_last_set_time is a private instance variable:
````
 _location_last_set_time: datetime.datetime = None
````

And there is no getter to get this time, so I could compute the newest between last_updated_at and _location_last_set_time
````
@property
    def location_latitude(self):
        return self._location_latitude

    @property
    def location_longitude(self):
        return self._location_longitude

    @property
    def location(self):
        return self._location_longitude, self._location_latitude

    @location.setter
    def location(self, value):
        self._location_latitude = value[0]
        self._location_longitude = value[1]
        self._location_last_set_time = value[2]
````

So at least the _last_location_last_set_time should be made public.
Better would be to have 3 date/time stamps, so the caller can distinguish between the two (if there is a use case) and also has an easy way to get the latest of the 2 combined.

But in general one would expect from the outside (the API users) could see immediately via a date/time stamp 'something' has been changed in the vehicle class, irrespective which data (location or other data).

**Comment by ZuinigeRijder** [comment]
I made a (temporary) fix for this issue in monitor.py.
Release 2.15.0: (temporary) fix for wrong date/time stamps in monitor.csv
https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/releases/tag/R2.15.0

**Comment by fuatakgun** [comment]
According to my tests, gps data and forced data don't need to be in sync.

Gps signal might be missing but having an internet connection is still feasible. In this case, fresh data has a different timestamp than gps data. Moreover, we are calling get location api which is definitely different (probably later) than fresh data timestamp.

**Comment by ZuinigeRijder** [comment]
> According to my tests, gps data and forced data don't need to be in sync.
> 
> Gps signal might be missing but having an internet connection is still feasible. In this case, fresh data has a different timestamp than gps data. Moreover, we are calling get location api which is definitely different (probably later) than fresh data timestamp.

In this case I only use cached server data, so no forced data!
Anyway, from the Vehicle class of point you would like to know the latest server timestamp and maybe you also have a use case to have access to the individual timestamps.

**Comment by fuatakgun** [comment]
if gps timestamp is greater than cached one and if we expose gps timestamp as last update time, it means, vehicle data is updated at that time, which is not correct.

Why don't we keep them separated in the api and let the consumers make the call. Api is intended to be low level with minimal business logic and consumers can use any of it freely without hidden adjustments.

Look at my car below, while location is very recent, vehicle data is 3 hours old.

![Screenshot_2023-01-03-10-29-09-346-edit_com.kia.connect.eu.jpg](https://user-images.githubusercontent.com/11085566/210330874-dd247d50-bcc7-4c75-b492-1d769fba7be3.jpg)

![Screenshot_2023-01-03-10-28-26-046-edit_com.kia.connect.eu.jpg](https://user-images.githubusercontent.com/11085566/210330900-189fc8fe-f5bf-4202-9ae3-d520f19368af.jpg)

**Comment by ZuinigeRijder** [comment]
But then the _location_last_set_time should be not protected, it should not start with an underscore.

**Comment by fuatakgun** [comment]
agree, we can expose this field to external usage

**Comment by fuatakgun** [comment]
Vehicle data was supposed to be data - whatever was coming from cached data - but, by the time, the library grew and it is a bit mixed use case now. Feel free to raise a PR to separate the classes.

**Comment by ZuinigeRijder** [comment]
Thanks for the merge, issue can be closed.
