### ISSUE TITLE
Feature request: tripinfo for specific month and specific day

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#248]
* Hyundai / Kia Connect version: 2.1.2 And Bluelink Android App 2.0.7
* Python version: 3.9.13
* Operating System: Windows 10

### Description
I have been able to sniff the Hyundai Bluelink Android App calls for my IONIQ 5 in Europe, unaware if this information is available in other regions. Especially I was interested in the detailed **"My Trip"** information, available in the Bluelink App via ... -> MyTrips

See screenshots from the Bluelink Android App:

![MyTrips1_2023-01-07-11-26-50](https://user-images.githubusercontent.com/90704821/211148792-b40f134a-e21e-444e-8faf-3918760db778.png)

![MyTrips2_2023-01-07-11-27-08](https://user-images.githubusercontent.com/90704821/211148798-dc35f596-ad29-4fc6-9d94-4b16febfa1fb.png)

The URL to get this tripinfo is:
**POST /api/v1/spa/vehicles/[id]/tripinfo HTTP/1.1**

So this looks like it is somethink like drvhistory in Europe:
POST /api/v1/spa/vehicles/[id]/drvhistory

There are apparently 2 variants, one to get month info and one to get detailed day info, the difference is in the post message request:

### Month info example:
POST data request:
````
{"tripPeriodType":0,"setTripMonth":"202301"}
````

POST data response (pretty print):
````
{
  "retCode": "S",
  "resCode": "0000",
  "resMsg": {
    "tripPeriodType": 0,
    "monthTripDayCnt": 4,
    "tripDayList": [
      {
        "tripDayInMonth": "20230102",
        "tripCntDay": 2
      },
      {
        "tripDayInMonth": "20230103",
        "tripCntDay": 5
      },
      {
        "tripDayInMonth": "20230104",
        "tripCntDay": 2
      },
      {
        "tripDayInMonth": "20230106",
        "tripCntDay": 4
      }
    ],
    "tripDrvTime": 172,
    "tripIdleTime": 17,
    "tripDist": 123,
    "tripAvgSpeed": 46.5,
    "tripMaxSpeed": 108
  },
  "msgId": "...."
}
````

### Day info example:
POST data request:
````
{"tripPeriodType":1,"setTripDay":"20230103"}
````
Post data response (pretty print):
````
{
  "retCode": "S",
  "resCode": "0000",
  "resMsg": {
    "tripPeriodType": 1,
    "offset": 1,
    "dayTripList": [
      {
        "tripDay": "20230103",
        "dayTripCnt": 5,
        "tripDrvTime": 93,
        "tripIdleTime": 12,
        "tripDist": 67,
        "tripAvgSpeed": 51.8,
        "tripMaxSpeed": 102,
        "tripList": [
          {
            "tripTime": "192151",
            "tripDrvTime": 8,
            "tripIdleTime": 0,
            "tripDist": 7,
            "tripAvgSpeed": 58,
            "tripMaxSpeed": 98
          },
          {
            "tripTime": "185404",
            "tripDrvTime": 12,
            "tripIdleTime": 1,
            "tripDist": 7,
            "tripAvgSpeed": 39,
            "tripMaxSpeed": 69
          },
          {
            "tripTime": "143439",
            "tripDrvTime": 34,
            "tripIdleTime": 5,
            "tripDist": 20,
            "tripAvgSpeed": 45,
            "tripMaxSpeed": 86
          },
          {
            "tripTime": "123318",
            "tripDrvTime": 25,
            "tripIdleTime": 3,
            "tripDist": 27,
            "tripAvgSpeed": 76,
            "tripMaxSpeed": 102
          },
          {
            "tripTime": "120539",
            "tripDrvTime": 14,
            "tripIdleTime": 3,
            "tripDist": 6,
            "tripAvgSpeed": 41,
            "tripMaxSpeed": 73
          }
        ]
      }
    ]
  },
  "msgId": "...."
}
````

### How to sniff
For the ones who also want to be able to sniff the calls from the App, this is how I did it (do it at your own risk):
- Installed NoxPlayer emulator in Windows 10 and emulate Android 5
- Installed Burp Suite Community Edition on Windows 10
- Then followed this guide without installing Bluelink App yet: [Android App Traffic Decryption using Nox Player - Windows Guide](https://archive.ph/k1hIG)
- Disabled Root (because Bluelink App will not work on rooted device) and proxy in Android emulator, installed Bluelink App and login with my credentials (with proxy I could not login?)
- Enabled proxy and opened Bluelink App and in the Burp Suite the decoded https requests/responses were available

**Comment by ZuinigeRijder** [comment]
My proposal would be to add the following public methods to Vehicle.py:
- get_tripinfo_month(yyyymm_string)
- get_tripinfo_day(yyyymmdd_string)

Only for Europe these will be implemented, something like KiaUvoApiEU.py-> _get_driving_info()
And also a mapping to a dataclass like DailyDrivingStats.

Note that the caller needs to call these new methods and decide for which month(s) and day(s) to get the tripinfo, because maybe already processed months and days are stored locally by the caller. Typically the caller will get the trips of the current month and after the last day tripinfo was previously requested.

**Comment by cdnninja** [comment]
Where do you get the [id] value for the URL?    Vehicle is a data class so contains no calls.   This would sit in vehicle manager I believe.  I am thinking we create a data class for this though much like this:  https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/cbec5e0bc3cd5e1bc57c3f025e2b4165148f3712/hyundai_kia_connect_api/Vehicle.py#L13-L24

Thoughts?

**Comment by cdnninja** [comment]
I am trying to mock up something but torn on how to model this since you can ask for historical data.  We could return an object that just is what is requested but that would be the only time we do that in the library.  Or we could take a date, or a range and process that and store it in a data class for consumption.  I am almost leaning toward the second.

@fuatakgun  @ZuinigeRijder  thoughts on the right approach?

**Comment by ZuinigeRijder** [comment]
The [id] is the Vehicle id.
I would not prefill the data, but the user of the library calls the methods on the VehicleManager class with the appropriate parameters, including the Vehicle id. And only at that time the requested tripinfo data is returned. If the user of the library is not interested in this tripinfo, then those methods should not be called.  

This is the same approach as in the Bluelink App, as long as you do not open the MyTrips page, no tripinfo data will be fetched. In the myTrips page only the month trip info is asked. When you select a day, then the tripinfo of that day is asked.

**Comment by cdnninja** [comment]
I am not thinking pre-filling but rather storing.  So having essentially a dataclass nested within the vehicle that holds any days you have requested the data for.  Definitely wouldn't call this unless requested. I started a basic outline of the data side here:   https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/250

Feedback would be good as I suspect you would be the largest consumer of this.  That dataclass could either be stored in vehicle or returned or both. 

I was hoping to keep the date request as a datetype but not sure how to handle month. Could just have a date as the request and ignore the day.

**Comment by fuatakgun** [comment]
1- it could be an attribute of vehicle class, initially None
2- when respective api call is executed, it could be written inside vehicle class
3- this should not be part of forced or cached update, totally independent

**Comment by cdnninja** [comment]
> 

Yes this is what I was thinking, however a Dataclass the is a item stored in vehicle class.  Since this is more complex data.

**Comment by cdnninja** [comment]
The vehicle file shows roughly an attempted approach here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/250/files

Still need to figure out datatype classes for day_trip and trip.

**Comment by ZuinigeRijder** [comment]
I really think you want to have two separate methods, one for the month tripinfo and one for the day tripinfo. The first one you provide the month (yyyymm string) and the second one the day of the month (yyymmdd string). 

The caller decides which month (or loops itself over the months not yet gathered).
The caller also loops over the days of that month not yet gathered trip info of.
At least the hyundai_kia_connect_monitor would use it that way.

And also I can imagine that in HomeAssistant a month calendar is presented with the days (indication per day if trips occurred) and the user selects a day and the trip info of that day is presented. So the roundtrips are limited (1 call for the month, 1 call for the day when a day is selected).

So it is just mimicking the json results of month tripinfo to a dataclass and day tripinfo to another dataclass.

**Comment by cdnninja** [comment]
From a data type I was hoping to avoid the string for a day or month and use the python datatype but I do thing string may be the easier way to go for month and would want consistency. 

As for separate methods for the two calls are you able to help me unpack that one?  It looks like it is the same endpoint just passing 0 or 1 depending on the type of data you want so was considering doing the same and dealing with the complexity of data response within the calls and data class. 

For sure agree on the looping topic, I am happy to leave it just as a single on demand type call.

**Comment by ZuinigeRijder** [comment]
yes, I can provide some code, but that will be monday then. I would expect one protected method, which is called with 0 or 1 and the public methods will convert the json result to the appropriate dataclass

**Comment by cdnninja** [comment]
Gotcha that makes sense.  Always happy to have contributions.  You are doing some great work on your monitoring project by the way.

**Comment by ZuinigeRijder** [comment]
@cdnninja I have made a small standalone test program with code to fill the datastructures.
I hardcoded the month and day strings for testing purposes, instead of calling the hyundai_kia_connect_api/bluelink API.

So probably you can copy/paste most of the solution into your solutions.

Note that I made 2 different methods from the outside, to hide the inner knowledge about tripPeriodType:
- update_month_trip_info
- update_day_trip_info

Probably error handling needs to be added.

````
""" Example decoding tripinfo """
import json
import dataclasses

MONTH_TRIPINFO_DEBUG = """
{
  "retCode": "S",
  "resCode": "0000",
  "resMsg": {
    "tripPeriodType": 0,
    "monthTripDayCnt": 4,
    "tripDayList": [
      {
        "tripDayInMonth": "20230102",
        "tripCntDay": 2
      },
      {
        "tripDayInMonth": "20230103",
        "tripCntDay": 5
      },
      {
        "tripDayInMonth": "20230104",
        "tripCntDay": 2
      },
      {
        "tripDayInMonth": "20230106",
        "tripCntDay": 4
      }
    ],
    "tripDrvTime": 172,
    "tripIdleTime": 17,
    "tripDist": 123,
    "tripAvgSpeed": 46.5,
    "tripMaxSpeed": 108
  },
  "msgId": "223d9e81-2c3a-4784-9526-a835ab4dca4c"
}
"""

DAY_TRIPINFO_DEBUG = """
{
  "retCode": "S",
  "resCode": "0000",
  "resMsg": {
    "tripPeriodType": 1,
    "offset": 1,
    "dayTripList": [
      {
        "tripDay": "20230103",
        "dayTripCnt": 5,
        "tripDrvTime": 93,
        "tripIdleTime": 12,
        "tripDist": 67,
        "tripAvgSpeed": 51.8,
        "tripMaxSpeed": 102,
        "tripList": [
          {
            "tripTime": "192151",
            "tripDrvTime": 8,
            "tripIdleTime": 0,
            "tripDist": 7,
            "tripAvgSpeed": 58,
            "tripMaxSpeed": 98
          },
          {
            "tripTime": "185404",
            "tripDrvTime": 12,
            "tripIdleTime": 1,
            "tripDist": 7,
            "tripAvgSpeed": 39,
            "tripMaxSpeed": 69
          },
          {
            "tripTime": "143439",
            "tripDrvTime": 34,
            "tripIdleTime": 5,
            "tripDist": 20,
            "tripAvgSpeed": 45,
            "tripMaxSpeed": 86
          },
          {
            "tripTime": "123318",
            "tripDrvTime": 25,
            "tripIdleTime": 3,
            "tripDist": 27,
            "tripAvgSpeed": 76,
            "tripMaxSpeed": 102
          },
          {
            "tripTime": "120539",
            "tripDrvTime": 14,
            "tripIdleTime": 3,
            "tripDist": 6,
            "tripAvgSpeed": 41,
            "tripMaxSpeed": 73
          }
        ]
      }
    ]
  },
  "msgId": "9c188edf-b135-49b7-ba4a-e78b97eae56d"
}
"""


def _get_trip_info(
    # self,
    # token,
    # vehicle,
    date_string: str,
    trip_period_type: int
) -> str:
    """ protected comveniemce method to get trip info"""
    if trip_period_type == 0:
        post_json_msg = {"tripPeriodType": 0, "setTripMonth": date_string}
    elif trip_period_type == 1:
        post_json_msg = {"tripPeriodType": 1, "setTripDay": date_string}
    else:
        print("ERROR")

    print(post_json_msg)
    # url = self.SPA_API_URL + "vehicles/" + vehicle.id + "/tripinfo"
    # responseAlltime = requests.post(
    #     url,
    #     json=post_json_msg,
    #     headers=self._get_authenticated_headers(token),
    # )
    # return responseAlltime.json()

    # next lines are for development purposes
    if trip_period_type == 0:
        return json.loads(MONTH_TRIPINFO_DEBUG)
    return json.loads(DAY_TRIPINFO_DEBUG)


@dataclasses.dataclass
class TripInfo:
    """ Trip Info """
    hhmmss: str = None  # will not be filled by DayTripInfo.summary
    drive_time: int = None
    idle_time: int = None
    distance: int = None
    avg_speed: float = None
    max_speed: int = None


@dataclasses.dataclass
class DayTripCounts:
    """Day trip info """
    yyyymmdd: str
    trip_count: int


@dataclasses.dataclass
class MonthTripInfo:
    """ Month Trip Info """
    yyyymm: str = None
    summary: TripInfo = None
    day_list: list[DayTripCounts] = dataclasses.field(default_factory=list)


@dataclasses.dataclass
class DayTripInfo:
    """ Day Trip Info"""
    yyyymmdd: str = None
    summary: TripInfo = None
    trip_list: list[TripInfo] = dataclasses.field(default_factory=list)


def update_month_trip_info(
    # self,
    # token,
    # vehicle,
    yyyymm_string
) -> MonthTripInfo:
    """ update month trip info """
    json_result = _get_trip_info(
        # self,
        # token,
        # vehicle,
        yyyymm_string,
        0
    )
    msg = json_result["resMsg"]
    result = MonthTripInfo(
        yyyymm=yyyymm_string,
        day_list=[],
        summary=TripInfo(
            drive_time=msg["tripDrvTime"],
            idle_time=msg["tripIdleTime"],
            distance=msg["tripDist"],
            avg_speed=msg["tripAvgSpeed"],
            max_speed=msg["tripMaxSpeed"]
        )
    )

    for day in msg["tripDayList"]:
        processed_day = DayTripCounts(
            yyyymmdd=day["tripDayInMonth"],
            trip_count=day["tripCntDay"]
        )
        result.day_list.append(processed_day)

    return result


def update_day_trip_info(
    # self,
    # token,
    # vehicle,
    yyyymmdd_string
):
    """ update day trip info """
    json_result = _get_trip_info(
        # self,
        # token,
        # vehicle,
        yyyymmdd_string,
        1
    )
    day_trip_list = json_result["resMsg"]["dayTripList"]
    if len(day_trip_list) > 0:
        msg = day_trip_list[0]
        print("Message=" + str(msg))
        result = DayTripInfo(
            yyyymmdd=yyyymmdd_string,
            trip_list=[],
            summary=TripInfo(
                drive_time=msg["tripDrvTime"],
                idle_time=msg["tripIdleTime"],
                distance=msg["tripDist"],
                avg_speed=msg["tripAvgSpeed"],
                max_speed=msg["tripMaxSpeed"]
            )
        )
        for trip in msg["tripList"]:
            processed_trip = TripInfo(
                hhmmss=trip["tripTime"],
                drive_time=trip["tripDrvTime"],
                idle_time=trip["tripIdleTime"],
                distance=trip["tripDist"],
                avg_speed=trip["tripAvgSpeed"],
                max_speed=trip["tripMaxSpeed"]
            )
            result.trip_list.append(processed_trip)

    return result


# testing

# == print_indent ==========================================================
def print_indent(indent):
    """print indent"""
    print()
    i = 0
    while i < indent:
        i += 1
        print('    ', end='')


# == print_indented ==========================================================
def print_indented(string):
    """print indented"""
    indent = 0
    for char in string:
        if char == '{' or char == '[' or char == '(':
            print_indent(indent)
            print(char, end='')
            indent += 1
            print_indent(indent)
        elif char == '}' or char == ']' or char == ')':
            indent -= 1
            print_indent(indent)
            print(char, end='')
        elif char == ',':
            print(char, end='')
            print_indent(indent)
        else:
            print(char, end='')

    print()


update_month_trip_info_result = update_month_trip_info("202301")
print(f"result: {update_month_trip_info_result}")
print_indented(str(update_month_trip_info_result))

update_day_trip_info_result = update_day_trip_info("20230103")
print(f"result: {update_day_trip_info_result}")
print_indented(str(update_day_trip_info_result))
````

**Comment by cdnninja** [comment]
Quick note I will be gone for a few days so won't be able to get to this for a week or so.   Happy to receive a PR if you are in a hurry but also happy to work on it when back.  Whichever you prefer!

**Comment by ZuinigeRijder** [comment]
@cdnninja Thanks for letting me know. I will go ahead and create a Pull Request.

**Comment by ZuinigeRijder** [comment]
@cdnninja I created a pull request:
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/259
