### ISSUE TITLE
dt.datetime.strptime(value, "%I%M %p").time() throws TypeError

### ISSUE THREAD

**Issue by zulufoxtrot** [Hyundai-Kia-Connect/hyundai_kia_connect_api#265]
* Hyundai / Kia Connect version: ?
* Python version: 3.10
* Operating System: ?

### Description

Error encountered by @Adi3000, see https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/255

when vehicle.ev_first_departure_time is fetch _get_time_from_string isn't retreivable because of :
```
File "/usr/local/lib/python3.10/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 587, in _update_vehicle_properties
vehicle.ev_first_departure_time = self._get_time_from_string(
File "/usr/local/lib/python3.10/dist-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 276, in _get_time_from_string
value = dt.datetime.strptime(value, "%I%M %p").time()
TypeError: 'NoneType' object is not callable
```

See my reply here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/255#issuecomment-1387476130

**Comment by Adi3000** [comment]
(sorry did'nt saw the issue)

Here some dumps to investigate : 
I forgot to say that I use python 3.10 : 
[Kona_dump_fork_3.10.txt](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/files/10472273/Kona_dump_fork_3.10.txt)
I also install a new VM on another pc with python 3.9 (I use python 3.10 on my server)
[Kona_dump_main_3.9.txt](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/files/10472274/Kona_dump_main_3.9.txt)

We can see some diff on date/time  : they may be separated on 3.10 ^^ Is that something which could break some features ?
The dump is extracted by : 
```
vm = VehicleManager(region=1, brand=2, username=username, password=password, pin=pin)
vm.check_and_refresh_token()
vm.update_all_vehicles_with_cached_state()
pprint.PrettyPrinter(indent=2,compact=True,sort_dicts=True).pprint(vm.vehicles)
```


Also maybe it was a cache a python cache issue (don't know why cause it was a fresh install). But, when executing the [plugin.py](https://github.com/CreasolTech/domoticz-hyundai-kia/blob/master/plugin.py) from python prompt, 

Next, I've try the sequence on main (WSL, python 3.9): 
```
>>> vm.check_and_refresh_token()
>>> vm.force_refresh_all_vehicles_states()
>>> vm.update_all_vehicles_with_cached_state()
```
And nothing wrong append anymore. On the 2023-01-09 it happens everytime until I try the #255 fix.

We may close this issue, and reopen it when I encouter this bug again (I'll then push the Vehicule dump which is astake)
Thank for your investigation

**Comment by Adi3000** [comment]
For information : 

**Hyundai / Kia Connect version:** hyundai_kia_connect_api-2.3.1
**Python version:** 3.10
**Operating System:** Debian (bookworm/testing)

**Comment by Adi3000** [comment]
note : extraction [Kona_dump_main_3.9.txt](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/files/10472274/Kona_dump_main_3.9.txt) was made over version 2.4.3, but I've just rollbacked to 2.3.1 and it works fine. Maybe it was a temporary API bug, but that strange that it crash after getting all data...

**Comment by zulufoxtrot** [comment]
I'm pretty sure it's not an API bug (https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/255#issuecomment-1387476130)
And I couldn't find anything related to datetime handling in python 3.10's changelog
My best guess is there is something wrong in your environment. Either python version or dependencies. It is preferable to run the library in a virtual environment with the exact package versions listed in requirements.txt.
Closing this issue for now.

**Comment by Adi3000** [comment]
Hard to do venv with my actual legacy+custom configuration of Domoticz environment execution, but Dockerizing it is in my so long Todo list :) thanks again
