### ISSUE TITLE
odometer not being updated while car in motion

### ISSUE THREAD

**Issue by eili77** [Hyundai-Kia-Connect/hyundai_kia_connect_api#298]
Hyundai / Kia Connect version: latest
Python version: 3.11
Operating System: Windows & Unix

### Description

I don't see odometer value only being updated at end of a trip, hence no updates while the car is in motion.

### What I Did

```
I used 
- force_refresh_all_vehicles_states()
and 
- update_all_vehicles_with_cached_state()
to get latest data while car was in motion
```

Is this a known limitation?

**Comment by cdnninja** [comment]
That's correct.   This is how the API works.  Unfortunately nothing we can do on this one.

**Comment by eili77** [comment]
@cdnninja 
Thanks for letting me know!
