### ISSUE TITLE
Can trip information shown in BLUELINK app been made available?

### ISSUE THREAD

**Issue by eili77** [Hyundai-Kia-Connect/hyundai_kia_connect_api#299]
Hyundai / Kia Connect version: latest
Python version: 3.11
Operating System: Windows & Unix

### Description

Would be greate to have individual trip data made available the the api.
I'm referring to the data that is shown in the BLUELINK app in the menu section: /MORE/My trips/...

### What I Did

```
I couldn't find any of the trip data in the payload of the API services.
```

**Comment by ZuinigeRijder** [comment]
I assume this is for USA, because for Europe this is already available: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/248

In this issue is also mentioned, how you can sniff the calls when you open the page with tripinfo in the Bluelink App.

**Comment by cdnninja** [comment]
@eili77  Which region are you in?

**Comment by cdnninja** [comment]
Actually I see from the other post you are in the EU.  I see our main docs aren't great on this but near the bottom it explains how to use it.  Call update_month_trip_info

**Comment by eili77** [comment]
@cdnninja Thanks for the tip. 
I thought these are the daily totals and not the individual trips. Probably my mistake... I will check again.

**Comment by ZuinigeRijder** [comment]
@eili77 You can look here how it can look: [hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor#introduction-hyundai_kia_connect_monitor)

**Comment by eili77** [comment]
@cdnninja Great, thanks a lot!

**Comment by ZuinigeRijder** [comment]
@cdnninja So I think this issue can be closed.
