### ISSUE TITLE
vm.check_and_refresh_token() suddenly throws constantly exception: {KeyError} 'intUserId'

### ISSUE THREAD

**Issue by eili77** [Hyundai-Kia-Connect/hyundai_kia_connect_api#309]
* Hyundai / Kia Connect version: newest
* Python version: 3.11
* Operating System: Ubuntu

`vm.check_and_refresh_token()` started suddenly to throw exception `{KeyError} 'intUserId'`

Anybody else experiencing the same?

**Comment by Boltify** [comment]
yes, did a reinstallation but cannot logon now!

**Comment by ot3** [comment]
I have a similar problem since 2023-04-02 it reports: KeyError: 'redirectUrl', followed immediately with {KeyError} 'intUserId':

`Traceback (most recent call last):
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 103, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 563, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
`

My code has been running fine for over a year; this must originate from a change made by Kia.

**Comment by stefan-hausmeister** [comment]
additional information:

api-call https://prd.eu-ccapi.kia.com:8080/api/v1/user/signin
returns:
{
    "errId": "b54cecdd-38b3-4c6f-917b-3271f6c107ac",
    "errCode": "4002",
    "errMsg": "Invalid parameters"
}
instead of resultset with 'redirectUrl'.

**Comment by joschiservice** [comment]
There was an update to the Kia & Hyundai app one day ago. Seems that they have changed something in the authentication process. Please wait until the maintainers of this repository will publish a fix.

**Comment by hmmbob** [comment]
Also reported here: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/618

**Comment by mjmeierhoefer** [comment]
Having the same error:

```
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1242, in _get_authorization_code_with_form
    intUserId = "".join(parse_qs(parsed_url.query)["intUserId"])
KeyError: 'intUserId'

```

**Comment by pos-ei-don** [comment]
+1

**Comment by cdnninja** [comment]
Does everyone's native app work?

**Comment by zulufoxtrot** [comment]
Yes, it works on my native app.
@cdnninja I can take a look right now, unless you want to?

**Comment by rindlerblabla** [comment]
My native app is working as well (EU). Same issue when reloading the integration.

**Comment by DragonQ** [comment]
Same here. Kia Connect app works fine, Home Assistant errors with "Retrying setup: Config Not Ready: 'intUserId'". EU region.

**Comment by faipassa** [comment]
App still work but api no more :-(
Looking forward to getting news

**Comment by cdnninja** [comment]
> Yes, it works on my native app.
> 
> @cdnninja I can take a look right now, unless you want to?

Go for it.  I don't have an easy way to test fixes. 

@fuatakgun was also looking at this.  

We think this may be the v1 apis being discontinued. This api hasn't been cutover.

**Comment by zulufoxtrot** [comment]
For context, there are 2 ways to login:
- "redirect url" / API: default, not working, not sure for how long it's been broken
- form: fallback, most likely what broke today.
The form method works up to /auth/realms/eukiaidm/login-actions/required-action.
After that I'm not sure what to do.
I dumped the mobile app traffic and while it does visit this URL, it is redirected immediately to the next phase. It's not the case with the library.
Sorry, that's all I can do for today.

**Comment by fuatakgun** [comment]
The initial method is working for me and some specific set uf users (long story about uvo, kia connect, account migration...). When account migration came up for some users (accounts created before 2021 - not sure about exact time) fallback option is created which is redirecting between multiple UVO servers.

I am not able to replicate the issue locally until i have access to account credentials having the problem.

Until then, please share full debug logs over email (fuatakgun@gmail.com) after redacting any sensitive information.

**Comment by Maaxion** [comment]
@fuatakgun I have now some debug logs. Will need to check what I need to strip from them before sending to you.

I looked at it a little bit, it seems like https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/cf49b76991e65bc3285f3c8550440bb0ff2d7cf3/hyundai_kia_connect_api/KiaUvoApiEU.py#L1202 here, the `response.url` no longer contains `intUserId`.

I do not know what that page used to contain, but now it is a minified JS page.

The full response.url returned is: ``` https://prd.eu-ccapi.hyundai.com:8080/web/v1/user/integration/auth?&locale=en```

**Comment by hmmbob** [comment]
> Until then, please share full debug logs over email ([fuatakgun@gmail.com](mailto:fuatakgun@gmail.com)) after redacting any sensitive information.

Logs sent

**Comment by booknownick** [comment]
+1

**Comment by ZuinigeRijder** [comment]
Is it possible, that only after using the newest Hyundai Bluelink or Kia Uvo Connect App, the new API becomes activated? Because I updated the Bluelink App this weekend on an Android phone (version 2.0.9), but I did not use it yet, did no refresh and no login/logout and for me the API is still working. So now I am afraid using the Bluelink App ;-)

**Comment by paulschermers** [comment]
> Is it possible, that only after using the newest Hyundai Bluelink or Kia Uvo Connect App, the new API becomes activated? Because I updated the Bluelink App this weekend on an Android phone (version 2.0.9), but I did not use it yet, did no refresh and no login/logout and for me the API is still working. So now I am afraid using the Bluelink App ;-)

Could be and I don't think so because I'm still using app version 2.0.8 (iOS) and my integrations (on HA and via bluelinky) both stopped working yesterday. App version 2.0.9 came out 2 days ago and isn't installed yet.

What struck me:
- Bluelinky was able to update at 3:30 AM (4/4/2023) at the latest
- HA was able to update at 20:38 (4-4-2023) at the latest

Error message from Bluelinky is as followed (removed 'client_id' and 'errId' out of precaution):
`[2023-04-05 11:24:59] warn: @EuropeanBrandAuthStrategy.login: Cannot find the argument userId, please use the following url and connect from a browser.
[2023-04-05 11:24:59] warn: https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=****&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect
[2023-04-05 11:24:59] error: @EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error Error: @EuropeanBrandAuthStrategy.login: Cannot find the argument userId in https://prd.eu-ccapi.hyundai.com:8080/web/v1/user/integration/auth?&locale=en.
        Please use the following url and connect from a browser, it may probably ask you to "Change your password" or "Accept the new conditions"
        Once done, try again.
        https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=****&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect
(node:519162) UnhandledPromiseRejectionWarning: ManagedBluelinkyError: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"***","errCode":"4003","errMsg":"Invalid values"}
    at U (/home/pi/node_modules/bluelinky/dist/index.js:17:11700)
    at ne.<anonymous> (/home/pi/node_modules/bluelinky/dist/index.js:17:39834)
    at Generator.throw (<anonymous>)
    at a (/home/pi/node_modules/bluelinky/dist/index.js:17:136)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:519162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:519162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by 4homeassistant** [comment]
@cdnninja do you remember the two posts from the guy that leaked the plans from Kia/Hyundai to change the API authentication behaviour in order to block 'non-regular' requests for the EUcc API? Could that be related?
I still have both mail notifications from his posts.
cc @fuatakgun

**Comment by Hacksore** [comment]
If someone has the fix please feel free to send a PR for bluelinky 🙏

**Comment by Flock82** [comment]
Submitting the Login-Form now returns a 302 redirect to an url containing "user_id" and "code". I tried to use those as a replacement for the intUserId and Authcode, but both failed, so there must be some changes to the endpoints for creating the AuthCode and/or Oauth-Token.
Existing Tokens continue to work and can also be refreshed, so seems no changes there. Also Stamps still work fine and receiving ControlTokens as well.

**Comment by povlhp** [comment]
They are removing functionality. Not sure they legally can do that here in Denmark. 

Guess I have to use fiddler again to reverse engineer new logon

**Comment by Bluhme1** [comment]
Could you do that? Sounds promising.
Greetings from a fellow countryman.
Lyder spændende. Håber det lykkes 
/Lars

**Comment by eili77** [comment]
I see there's a V3.4 out, which should resolve the issue.
Executing `pip install hyundai_kia_connect_api`, only installs V3.3.

Any suggestion would be much appreciated.

**Comment by cdnninja** [comment]
@Danielhiversen dropped a PR that should resolve this.  Try the latest of 3.1.6.    As a note 3.3 and 3.4 never existed from what I can tell.

**Comment by JeroenEeuwes** [comment]
> Any suggestion would be much appreciated.

In the mean time you can find the file KiaUvoApiEU.py on your system and replace it with the current one on Github: https://raw.githubusercontent.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/master/hyundai_kia_connect_api/KiaUvoApiEU.py

**Comment by bumperboy** [comment]
I installed again the integration using the master version and I'm again able to access the car's info in home assistant. For info, I have an ioniq 5 in BE

**Comment by eili77** [comment]
> @Danielhiversen dropped a PR that should resolve this. Try the latest of 3.1.6. As a note 3.3 and 3.4 never existed from what I can tell.

thanks, worked now, pip got me V3.1.6

**Comment by eili77** [comment]
@cdnninja and all other who helped to solve this bug: THANK YOU - awesome work!

**Comment by faipassa** [comment]
Upgraded my server with latest version 3.1.6 and works again.
Thanks a lot for your prompt action.
Greatings from France.

**Comment by zulufoxtrot** [comment]
Thanks to everyone involved.
I upgraded to 3.1.6 / latest commit, and unless I missed something, I'm still having issues.
Kia EU - account created late 2022 (I believe the creation date matters)

Method 1 (redirect URI) fails:

```
2023-04-08 18:00:06 laptop urllib3.connectionpool[59488] DEBUG https://prd.eu-ccapi.kia.com:8080 "POST /api/v1/user/silentsignin HTTP/1.1" 401 100
2023-04-08 18:00:06 laptop hyundai_kia_connect_api.KiaUvoApiEU[59488] DEBUG hyundai_kia_connect_api - silentsignin Response {'errId': '8dba1a60-4941-4dbd-8c45-5b3264c384be', 'errCode': '4010', 'errMsg': 'Require authentication'}
2023-04-08 18:00:06 laptop __main__[59488] ERROR generic error:
Traceback (most recent call last):
  File "/dev/python/kia_eniro_uvo/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 203, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/dev/python/kia_eniro_uvo/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1147, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
```

Request response:
```json
{"errId": "594485ce-145d-4c1b-852a-3f8020cc0518", "errCode": "4003", "errMsg": "Invalid values"}
```

Method 2 / fallback (login form) fails with the same error:
```
Traceback (most recent call last):
  File "/dev/python/kia_eniro_uvo/VehicleClient.py", line 251, in loop
    self.vm.check_and_refresh_token()
  File "/dev/python/kia_eniro_uvo/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 118, in check_and_refresh_token
    self.initialize()
  File "/dev/python/kia_eniro_uvo/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 62, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "/dev/python/kia_eniro_uvo/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 208, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/dev/python/kia_eniro_uvo/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1245, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
```

request response:
```json
{"errId": "9fad6803-0e68-4de0-a930-9cb4d52156cd", "errCode": "4010", "errMsg": "Require authentication"}
```
Maybe my account is a specific case?

**Comment by zulufoxtrot** [comment]
Can anyone with an "old" UVO account (created before 2020) test the PR above and report back?

**Comment by DragonQ** [comment]
> Can anyone with an "old" UVO account (created before 2020) test the PR above and report back?
I've never used this API directly, but the main code inside the  `./tests/eu_login_test.py` file runs successfully when my login details are correct and errors when they are not, so I think that means it's now working. :)

**Comment by zulufoxtrot** [comment]
Release 3.1.7 is up! Should fix the last known bugs.

**Comment by ot3** [comment]
Updated to 3.1.7 buts till not working. A new error this time in code that has previously worked for over a year:
```
Traceback (most recent call last):
  File "/home/pi/live/kia.py", line 819, in <module>
    main()
  File "/home/pi/live/kia.py", line 806, in main
    fetch_kia('SNAPSHOT')
  File "/home/pi/live/kia.py", line 567, in fetch_kia
    fetch_kia_and_store(session_mode)
  File "/home/pi/live/kia.py", line 541, in fetch_kia_and_store
    my_vehicle = fetch_vehicle()
  File "/home/pi/live/kia.py", line 164, in fetch_vehicle
    vm.force_refresh_vehicle_state(my_vehicle)
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 110, in force_refresh_vehicle_state
    vehicle = self.get_vehicle(vehicle_id)
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 69, in get_vehicle
    return self.vehicles[vehicle_id]
TypeError: unhashable type: 'Vehicle'
```

**Comment by cdnninja** [comment]
Thank you @zulufoxtrot for your work to fix that one! This thread and the kia_uvo thread speaks to the awesome community we have here.  Great work all!

**Comment by paulschermers** [comment]
Thanks for all the great work!

It's working for me in HA (IONIQ 5, NL)
It worked after I downloaded manually the file
`curl https://raw.githubusercontent.com/Hyundai-Kia-Connect/kia_uvo/master/custom_components/kia_uvo/manifest.json > manifest.json`

And did a restart of HA.

**Comment by paulschermers** [comment]
Thanks for all the great work!

The (non-force) update is now working in HA after I manually downloaded the file and did a restart.
`curl https://raw.githubusercontent.com/Hyundai-Kia-Connect/kia_uvo/master/custom_components/kia_uvo/manifest.json > homeassistant/custom_components/kia_uvo/manifest.json`

I've got the same error as ot3 mentoined when I do a force update.

`This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/kia_uvo/coordinator.py:159
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 10:25:19 PM (1 occurrences)
Last logged: 10:25:19 PM

Error executing service: <ServiceCall kia_uvo.force_update (c:***)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 49, in async_handle_force_update
    await coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_force_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 107, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(vehicle_id)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 318, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 735, in _get_forced_vehicle_state
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 108, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.RequestTimeoutError: Request timeout. - Request timeout.
`

**Comment by cdnninja** [comment]
> Thanks for all the great work!
> 
> The (non-force) update is now working in HA after I manually downloaded the file and did a restart. `curl https://raw.githubusercontent.com/Hyundai-Kia-Connect/kia_uvo/master/custom_components/kia_uvo/manifest.json > homeassistant/custom_components/kia_uvo/manifest.json`
> 
> I've got the a similar error as ot3 mentioned when I do a force update.
> 
> ```
> 
> Logger: homeassistant.core
> Source: custom_components/kia_uvo/coordinator.py:159
> Integration: Hyundai / Kia Connect (documentation, issues)
> First occurred: 10:25:19 PM (1 occurrences)
> Last logged: 10:25:19 PM
> 
> Error executing service: <ServiceCall kia_uvo.force_update (c:***)>
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
>     await coro_or_task
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
>     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
>   File "/config/custom_components/kia_uvo/services.py", line 49, in async_handle_force_update
>     await coordinator.async_force_update_all()
>   File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_force_update_all
>     await self.hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 107, in force_refresh_all_vehicles_states
>     self.force_refresh_vehicle_state(vehicle_id)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 112, in force_refresh_vehicle_state
>     self.api.force_refresh_vehicle_state(self.token, vehicle)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 318, in force_refresh_vehicle_state
>     state = self._get_forced_vehicle_state(token, vehicle)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 735, in _get_forced_vehicle_state
>     _check_response_for_errors(response)
>   File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 108, in _check_response_for_errors
>     raise error_code_mapping[response["resCode"]](response["resMsg"])
> hyundai_kia_connect_api.exceptions.RequestTimeoutError: Request timeout. - Request timeout.
> ```

Others are reporting no issue on forced up on the home assistant side could you retry?  Timeout makes it look temporary.

**Comment by zulufoxtrot** [comment]
@ot3 
`vm.force_refresh_vehicle_state(my_vehicle)` expects a string with the vehicle ID.
Looking at the commit history, this function used to expect a Vehicle object, but was changed in January 2023.
You were probably using an older version of the library, which would explain why it worked until you upgraded.
Just replace `my_vehicle` with `my_vehicle.id` and you should be good.

@paulschermers yup that sounds like a communication issue between the server and the car. Happens from time to time. Just try again later.

Closing this issue since all login problems seem fixed. :)

**Comment by ot3** [comment]
@zulufoxtrot: Spot on; that fixed it. Many thanks to you and others in the community to release a fix.
