### ISSUE TITLE
hyundai_kia_connect_api - _get_location failed

### ISSUE THREAD

**Issue by ultima-originem** [Hyundai-Kia-Connect/hyundai_kia_connect_api#324]
* Hyundai / Kia Connect version: 3.1.7
* Python version: 3.9
* Operating System: Ubuntu 22.04

### Description

I'm trying to use the geo location feature while extracting trip info. I'm getting the following warning: "hyundai_kia_connect_api - _get_location failed"

The vehicle manager is constructed as follows:
```
   vm = VehicleManager(
        brand=1,
        region=1,
        username=kia.username,
        password=kia.password,
        pin=kia.pin,
        geocode_api_enable=True,
        geocode_api_use_email=True
    )
```

What is the proper way to extract the geo location info per trip?

**Comment by cdnninja** [comment]
Are you looking for trip info or current location?

If _get_location failed that's more to do with current location than historical.

**Comment by ot3** [comment]
I was hoping to get the location per trip (end of trip?). I could be completely misinterpreting this feature. Is this possible?

**Comment by cdnninja** [comment]
Which region?

**Comment by ot3** [comment]
Sorry, I should have mentioned that: Europe.

**Comment by ot3** [comment]
That's were I started and that's what I got working but the example does not use any geo location features.

**Comment by cdnninja** [comment]
Geo location is just converting gps coordinates to address.  I haven't looked at trip details.   Does that include gps coordinates?

**Comment by ot3** [comment]
That's my assumption. The only info I've got is from the code. As shown in the opening post, you have to set geocode_api_enable to True.

**Comment by ZuinigeRijder** [comment]
@ot3 No, the trip info does not return gps coordinates, unfortunately. Note that [my monitor tool](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor#python-summarypy) tries to record locations for trips, but therefor you have to run the monitor.py script regularly.

**Comment by ZuinigeRijder** [comment]
@ot3 every time you call e.g. manager.update_all_vehicles_with_cached_state(), you can get the latest known address e.g. with the call vehicle.geocode[0] besides the coordinates (e.g. vehicle.location_longitude and vehicle.location_latitude).

Unfortunately Hyundai Bluelink or Kia Connect does not give back the coordinates with the trip info.

**Comment by ot3** [comment]
Thanks, I get it. A fairly useless  capability then.

**Comment by cdnninja** [comment]
> Thanks, I get it. A fairly useless capability then.

Sorry can you help us understand how converting the GPS coordinates to address is useless?    Feels like a shot that is uncalled for.    Numerous users requested this and use it regularly.    Yes you need to call the API regularly to track the address over time but that is a limitation of Hyundai not this repo.

**Comment by ot3** [comment]
I certainly did not want to imply any criticism on the code and I didn't say useless but fairly useless. This relative statement is important in this case. I would expect GPS coordinates to be available from whenever the car is switched off but I accept that the manufacturer simply does not provide that information. This capability would be vastly more useful than what is possible now and that was the background of my statement.

**Comment by ZuinigeRijder** [comment]
@ot3 In general this is true, the car sends the GPS coordinates to the server when the car is switched off. [With my tool](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor#introduction-hyundai_kia_connect_monitor) I ask every 15 minutes for the server values between 6.00 and 22:00, so that way I will get the history on a cheap Raspberry Pi. But the Bluelink API/Kia Connect API does not give back this history, so you have to  build it yourself, if you want this history. And then is this geocode feature very appreciated.

**Comment by ot3** [comment]
Agreed. I wasn't aware of your solution and will definitely look into it. Thanks for the info.
