### ISSUE TITLE
start_climat(): Temperature Question

### ISSUE THREAD

**Issue by Empor-co** [Hyundai-Kia-Connect/hyundai_kia_connect_api#34]
* Hyundai / Kia Connect version: 1.21.4

### Description

I'm trying to get `start_climat()` working, but struggle with the `set_temp`.

### What I Did
I tried the following:
```
        # https://github.com/Hacksore/bluelinky/issues/51#issue-658078545
        #options = ClimateRequestOptions(set_temp="22", duration=10, defrost=False, climate=False, heating=True)
        options = ClimateRequestOptions(set_temp="0FH", duration=10, climate=False, heating=True)
        vm.start_climate(id, options)
```
but get the following error:
```
  File "/home/user/PycharmProjects/bluelinx/venv/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 94, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/home/user/PycharmProjects/bluelinx/venv/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 362, in start_climate
    self.temperature_range.index(options.set_temp)
ValueError: '0FH' is not in list
```
I get the same error also when trying `"22"` as the `set_temp` value:
`ValueError: '22' is not in list`

What format/scale is used for the temperature control?

Thank you in advance.

**Comment by fuatakgun** [comment]
Can you try to send 22 as an integer or number?

**Comment by Empor-co** [comment]
So, I checked the car, the heating was working. :-)

Another catch seems to be `defrost`:

`options = ClimateRequestOptions(set_temp=22, duration=10, defrost=True, climate=False, heating=True)`
which throughs:
```
  File "/home/user/PycharmProjects/bluelinx/main.py", line 115, in on_message
    options = ClimateRequestOptions(set_temp=22, duration=10, defrost=True, climate=False, heating=True)
TypeError: ClimateRequestOptions.__init__() got an unexpected keyword argument 'defrost'
```
Did I miss-read the dataclass?

**Comment by fuatakgun** [comment]
You are right, we should fix it, thanks for bringing up

**Comment by cdnninja** [comment]
I think set_temp should be switched to a float to allow for 21.5 etc.  Climate will be a bool.  Feel free to drop a PR or I can make this change and do some testing this weekend.

**Comment by cdnninja** [comment]
Types have been corrected.

**Comment by cdnninja** [comment]
@Empor-co I am loving that you are a hair ahead of our re-write of home assistant integration.   You are catching bugs and greatly appreciate it!

**Comment by Empor-co** [comment]
@cdnninja: You're welcome. Glad I can help the project. I personally use it to feed my openHAB via MQTT.
