### ISSUE TITLE
login failed (HYUNDAY EUROPE)

### ISSUE THREAD

**Issue by rezzalex** [Hyundai-Kia-Connect/hyundai_kia_connect_api#361]
* Hyundai / Kia Connect version: latest
* Python version: 3.9
* Operating System: Domoticz official Container

### Description

I am using the domoticz-hyundai-kia python plugin for Domoticz  (https://github.com/CreasolTech/domoticz-hyundai-kia)

### What I Did
I am frequently updating both library and Domoticz plugin. Since end of may 2023,  then after this error message, I have downgrade charset normalizer to V 2.1 :

> 2023-07-17 11:07:24.689 Error: Ioniq5: Traceback (most recent call last):
> 2023-07-17 11:07:24.689 Error: Ioniq5: File "/opt/domoticz/userdata/plugins/domoticz-hyundai-kia/plugin.py", line 68, in <module>
> 2023-07-17 11:07:24.689 Error: Ioniq5: import requests
> 2023-07-17 11:07:24.689 Error: Ioniq5: File "/usr/local/lib/python3.9/dist-packages/requests/__init__.py", line 48, in <module>
> 2023-07-17 11:07:24.689 Error: Ioniq5: from charset_normalizer import __version__ as charset_normalizer_version
> 2023-07-17 11:07:24.690 Error: Ioniq5: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
> 2023-07-17 11:07:24.690 Error: Ioniq5: from .api import from_bytes, from_fp, from_path, is_binary
> 2023-07-17 11:07:24.690 Error: Ioniq5: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/api.py", line 5, in <module>
> 2023-07-17 11:07:24.690 Error: Ioniq5: from .cd import (
> 2023-07-17 11:07:24.690 Error: Ioniq5: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py", line 9, in <module>
> 2023-07-17 11:07:24.690 Error: Ioniq5: from .md import is_suspiciously_successive_range
> 2023-07-17 11:07:24.690 Error: Ioniq5: AttributeError: PyCapsule_Import "charset_normalizer.md__mypyc.init_charset_normalizer___md" is not valid

After that, I am not able to login anymore 

```
Ioniq5: *** check_and_refresh_token()...
2023-07-17 11:45:24.332 Ioniq5: AuthError: Login Failed
```

**Comment by cdnninja** [comment]
The above isn't an error from this package.  Email debug on this package and provide that please. 

What version are you on?  You say latest but I want to confirm that.

**Comment by rezzalex** [comment]
I just did a git pull.

Maybe I was on a 3.3.12 and now 3.3.13 : 

![image](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/assets/35136439/332480a5-0c7f-4999-8d77-383211d84004)

**Comment by rezzalex** [comment]
Solved by installing a precise version of request :

pip3 install requests==2.23.0
