### ISSUE TITLE
Use api for dynamic battery loading

### ISSUE THREAD

**Issue by cypridox** [Hyundai-Kia-Connect/hyundai_kia_connect_api#363]
Thanks for this interesting api. I own a Kia eNiro and intend to make a python application that supports dynamic battery loading. Besides figures from my P1 port and sun power forecast (Solcast) I need the actual battery capacity of the Kia. I think I can extract this from the api (car_battery_percentage, ev_battery_percentage, _ev_driving_range), but I have been puzzling how to do this without using home assistant. I succeeded to populate the address of the vehicle in the vehicle instance as described in the Read_me. Can you please provide me with some example code to read these figures just using Python?

**Comment by cdnninja** [comment]
Home page of this shows an example: 

```
from hyundai_kia_connect_api import *
vm = VehicleManager(region=2, brand=1, username="username@gmail.com", password="password", pin="1234")
vm.check_and_refresh_token()
vm.update_all_vehicles_with_cached_state()
print(vm.vehicles)
```

If you have that working you just need to grab the specific value instead.

**Comment by cypridox** [comment]
Ah, my RPI EDI only showed the vehicle ID, but now I see the dictionary contains the other fields as well, including the battery figures. Problem solved, thx :-)
