### ISSUE TITLE
KIA USA not handling "LOW" and "HIGH" values for climate.airTemp

### ISSUE THREAD

**Issue by lukemeyer** [Hyundai-Kia-Connect/hyundai_kia_connect_api#365]
* Hyundai / Kia Connect version:
3.3.13
* Python version:
* Operating System:
Linux (Homeassistant OS)

### Description

KIA USA airTemp is not handling the "LOW" and "HIGH" string values, causing an error in the HA component when it tries to set the sensor values (expects float). I was going to post in the HA component repo, but then I saw that the HyundaiBlueLinkAPIUSA.py was correctly handling this case, so I thought it belongs here.

Basically it looks like KiaUvoAPIUSA.py here https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/c8bb312e0f21da31beec5fb5e75938889e9c4be2/hyundai_kia_connect_api/KiaUvoAPIUSA.py#L288
needs to handle air temp the same way as HyundaiBlueLinkAPIUSA.py here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/c8bb312e0f21da31beec5fb5e75938889e9c4be2/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py#L263

My car (USA KIA Niro PHEV) is returning this status:
```
"vehicleStatus": {
  "climate": {
      "airCtrl": false,
      "defrost": false,
      "airTemp": {
          "value": "LOW",
          "unit": 1
      },
```

It looks like the value strings are not exactly the same so my thought is the KIA USA version should be this (but I am unable to test it in my setup)
```
air_temp = get_child_value(state, "lastVehicleInfo.vehicleStatusRpt.vehicleStatus.climate.airTemp.value")

if air_temp == "LOW":
    air_temp = self.temperature_range[0]
if air_temp == "HIGH":
    air_temp = self.temperature_range[-1]
if air_temp:
    vehicle.air_temperature = (air_temp, TEMPERATURE_UNITS[1])
```

**Comment by cdnninja** [comment]
Could you drop a pull request for this correction?

**Comment by cdnninja** [comment]
Thats for putting this fix in!  In home assistant if you "redownload" in HACS and select "Master" as the version it will have this fix.  Let me know if any issues.   Overnight a new version will auto release for general users.
