### ISSUE TITLE
Open & Close Charge Port

### ISSUE THREAD

**Issue by mepexi** [Hyundai-Kia-Connect/hyundai_kia_connect_api#411]
* Hyundai / Kia Connect version: 3.9
* Python version: 3.11
* Operating System: Windows

### Description

A simple test of checking charge port door status. Ignore that fact that I;m using the open for both.
```
from hyundai_kia_connect_api import *

```
email = "xxxxx"
password = "xxxxx"
region = 1  # Europe
brand = 1  # Kia
pin = ""  # Your PIN

vm = VehicleManager(region, brand, email, password, pin)
vm.check_and_refresh_token()
vm.check_and_force_update_vehicles(10)
vehicle_id, vehicle = next(iter(vm.vehicles.items()))
vehicle = vm.vehicles[vehicle_id]
print(vehicle_id)

print(f"{vehicle_id}")
print(f"{vehicle.name}")

if vehicle.ev_charge_port_door_is_open:
    print(f"{vehicle.ev_charge_port_door_is_open}")
    vm.open_charge_port(vehicle_id)
    print("closing charge port")
else:
    print("Charge port closed.")
    vm.open_charge_port(vehicle_id)
    
    
       
   This is the error I'm seeing
   
Unknown API response format: {'error': 'Access to this API has been disallowed'}

Has this function been blocked in this region?

**Comment by cdnninja** [comment]
I don't think it ever worked. It was really close but as I recall the person we were working with who had a port like this stopped responding.  Someone needs to sniff traffic and compare our payload to ours.

**Comment by Bubo08** [comment]
I sniffed the trafic and tried to adapt the code. I also tried other setter functions but I am always failing. As soon as v2 is used in the URL instead of v1 I will fail with the above message.

**Comment by cdnninja** [comment]
Could you try #506 and see if any different?

**Comment by asychow** [comment]
> Could you try #506 and see if any different?

Thank you very much for the work. I can confirm that it works with my EU(>2023) Hyundai. A few points (a bit off-topic)

- The traffic sniffed from the app uses a slightly different endpoint https://prd.eu-ccapi.hyundai.com:8080/api/v2/spa/vehicles/<token>/**ccs2/**control/portdoor, even though ccuCCS2ProtocolSupport is 0. The PR works anyways.
- For start/stop climate, start/stop charge and lock/unlock, the app also posts v2 requests, with the control token in the header. I don't know how the app decides to use v1 or v2.
- I can also confirm Force Update and set charge limits work

**Comment by cdnninja** [comment]
This is merged now so going to close it.
