### ISSUE TITLE
request to add total power generated to api data

### ISSUE THREAD

**Issue by WillemD61** [Hyundai-Kia-Connect/hyundai_kia_connect_api#416]
My request is to add total regenPwr to the api data.

In the file KiaUvoApiEU.py, please add at line 730 in the function _update_vehicle_drive_info the following line:
`vehicle.power_generated = get_child_value(state, "regenPwr")`

and in the file Vehicle.py at line 164 the following line
`power_generated: float = None  # Europe feature only`

I have tested the change in my local version.

**Comment by cdnninja** [comment]
Could you create a pr?

**Comment by WillemD61** [comment]
I don't know how to do that. I am not experienced on github.
When I click "create new pull request" I get a page and then don't know what to do.

**Comment by cdnninja** [comment]
If you go to the file where you want to make the change.  Make the edit off a fork it will let you create a PR.

**Comment by WillemD61** [comment]
I now created it. Since it required changes in two files I created two pull requests. I would expect to be able to combine this in one?

**Comment by cdnninja** [comment]
To combine them head into one of them.  At the top it will show your branch that it is coming from. Any chance in that branch will be part of this PR.  So click on it and edit within that branch.  

So if we consolidate to #417:

![image](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/assets/6373468/547cb868-ae1a-47bb-9324-35d5c816e4ee)

Click patch-2 which is your fork of this repo.

**Comment by WillemD61** [comment]
done, merged into 417, thanks for the explanation

**Comment by WillemD61** [comment]
pr 417 merged and closed
