### ISSUE TITLE
Invalid device id after start_charge() or stop_charge()

### ISSUE THREAD

**Issue by agx** [Hyundai-Kia-Connect/hyundai_kia_connect_api#424]
* Hyundai / Kia Connect version: 7cc05a454ac44150af3de6b594c6e7ed7bc4b187
* Python version: Python 3.11.5
* Operating System: Debian trixie/sid

### Description

I'm trying to start/stop charging which works but after sending the request, calls to `VehicleManager.force_refresh_all_vehicles_states()` fail with ` Invalid request body - Invalid deviceId`.
(see testcase below).

If I invoke `hyundai_kia_connect_api.VehicleManager` *again* I can again fetch the vehicle state.

### What I Did

Runnning this minimal test case

```python
import hyundai_kia_connect_api
import time
import sys

vm = hyundai_kia_connect_api.VehicleManager(region=1, brand=1, username='whatever', password='whatever', pin='1234')
vm.check_and_refresh_token()
vm.force_refresh_all_vehicles_states()
vid = list(vm.vehicles.keys())[0]

vm.stop_charge(vid)
time.sleep(10)
vm.check_and_refresh_token()
vm.force_refresh_all_vehicles_states()
```

leads to 

```
Traceback (most recent call last):
  File "/var/scratch/librem5/hyundai_kia_connect_api/testcase.py", line 13, in <module>
    vm.force_refresh_all_vehicles_states()
  File "/var/scratch/librem5/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 113, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(vehicle_id)
  File "/var/scratch/librem5/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 118, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/var/scratch/librem5/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 347, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/scratch/librem5/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 765, in _get_forced_vehicle_state
    _check_response_for_errors(response)
  File "/var/scratch/librem5/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoApiEU.py", line 113, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId. 
```

However if I do:

```
vm.token = None
```

after the `stop_charge()` API request things work as expected. Is this an API usage error on my side or are we supposed to reset the token after each request (basically forcing a relogin)?

**Comment by fuatakgun** [comment]
Sadly, this is a known problem, one of us needs to deep dive and fix the issue.

This would happen after each push notification generating command and device id used by this integration would be invalidated because we are failing to receive the notifications as expected.

**Comment by fuatakgun** [comment]
When you set the token to null, login flow would be initialized so you would receive a new token with a new device id.

**Comment by fuatakgun** [comment]
Yes, push notifications through Google Firebase (GCM) or Apple one.

My theory is that we must receive and acknowledge the notifications so we can stay alive but i need more time to validate this.

**Comment by fuatakgun** [comment]
And open to any help :-)

**Comment by cdnninja** [comment]
This should be fixed now.

**Comment by agx** [comment]
@cdnninja can you point me to the commit. I didn't spot anything related.

**Comment by cdnninja** [comment]
@agx https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/e61836eca3d5017e85a2e33f2a180b8d095b4bd2

**Comment by agx** [comment]
@cdnninja looks fixed here too, thanks!
