### ISSUE TITLE
Vehicle.odometer is string instead of float for HyundaiBlueLinkAPIUSA.py

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#433]
* Hyundai / Kia Connect version:  v3.10.5
* Python version: Python 3.9.13
* Operating System: Windows 10 + Raspberry Pi BullsEye

### Description

A user (USA, Bluelink, IONIQ 5) is using my [hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor). The problem is that it expects a float for Vehicle.odometer, but apparently for HyundaiBlueLinkAPIUSA.py it returns a string in miles, e.g. "522".

I would expect that this Vehicle.odometer string was converted to a float. I assumed it was a float for doing calculations and could use .f formats. Of course I can change it only at my side in hyundai_kia_connect_monitor, but would it not be better to convert it to float in the setter in hyundai_kia_connect_api? I also need to get the odometer_unit and missing a getter for this (only protected Vehicle._odometer_unit is available).
 
### What I Did

I made local modifications to Vehicle.py and utils.py, to safely convert a non-float to float.

Added get_float method to utils.py
````
def get_float(value):
    if value is None:
        return None
    if isinstance(value, float):
        return value
    if isinstance(value, int):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value)
        except ValueError:
            return value  # original fallback
    return value  # original fallback
````

Added get_float call and added Vehicle.odometer_unit to Vehicle.py 
```
    @property
    def odometer_unit(self):
        return self._odometer_unit

    @odometer.setter
    def odometer(self, value):
        float_value = get_float(value[0])
        self._odometer_value = float_value
        self._odometer_unit = value[1]
        self._odometer = float_value
```

I can make a pull request if you find this approach is how it should be.

**Comment by dbolger** [comment]
Out of curiosity, is this returning the actual float value of the odometer? i.e. 1,234.1 miles?
If we have that level of precision coming back from BlueLink, I see no reason for not reflecting that data the same way on the API.

**Comment by ZuinigeRijder** [comment]
@dbolger Nope, it does return a string without decimals.

Part of the Vehicle dump of the user, where the 552 is the actual mileage in the car.
```
         _odometer='552',
         _odometer_value='552',
         _odometer_unit='mi',
```

**Comment by dbolger** [comment]
@ZuinigeRijder That's a shame, but that makes sense now that I look at the BlueLink app on my phone.

**Comment by dbolger** [comment]
I haven't had the chance to review, but does the remaining range return a float from Hyundai or in this API? At least in Home Assistant, I'm seeing that value as with a decimal place. That may be that integration doing that, but some consistency would be nice.

**Comment by fuatakgun** [comment]
Home assistant integration is taking care of it.

**Comment by ZuinigeRijder** [comment]
@cdnninja I can make a pull request if you find this approach is how it should be.

**Comment by cdnninja** [comment]
Works for me.  I am not familiar enough with best practice to comment.

**Comment by ZuinigeRijder** [comment]
@cdnninja See this [pull request](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/435) #435
