### ISSUE TITLE
Feature: [US] Expose EV Trip Details

### ISSUE THREAD

**Issue by DanielRussell** [Hyundai-Kia-Connect/hyundai_kia_connect_api#473]
* Hyundai / Kia Connect version: 5.1.8
* Python version: 3.11
* Operating System: macOS / Linux

### Description

The MyHyundai app shows some details about recent trips (Vehicle Status -> EV Trip Details).  I would like to expose these stats to arbitrary applications, HomeAssistant, etc.

### What I Did

Setup Charles Proxy.  Launch the MyHyundai app and navigate to the EV Trip Details.  Copy the cURL request from Charles and verify its functionality via the CLI.  Then figure out how to add this API call and resulting data to the codebase.

**Comment by ZuinigeRijder** [comment]
[See this issue](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/248), where I integrated this in KiaUvoApiEU.py for Hyundai Bluelink and Kia Uvo. Maybe this helps with a similar approach?
