### ISSUE TITLE
disappearing data, readings going backwards

### ISSUE THREAD

**Issue by WillemD61** [Hyundai-Kia-Connect/hyundai_kia_connect_api#494]
It is probably an issue of the Hyundai/Kia cloud but I am raising an issue anyway just to check whether anyone else has this problem as well.

Below is an example of two consecutive readings from the cloud by the KiaUvoApiEU program with debug turned on. I only did some formatting for readability.

As you can see the totalPwrCsp and other power readings, but also calculativeOdo reading, are reduced from one reading to the next, so are going backwards, while these are supposed to be total cumulative readings. Totals for period 0 are reduced, totals for period 1 are slightly increased, the sum of the two is reduced.

The sum of the details for drivingperiod 1 matches the total of drivingperiod 0 in both cases. The reduction is in the oldest month.

I still need to analyse other cases where this happens and see whether I can find an explanation. Maybe some data is dropped after 3 months? I also noted in the app that no data older than 3 months is available.

```
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_driving_info responseAlltime {'retCode': 'S', 'resCode': '0000', 'resMsg': {'drivingInfo': [
{'drivingPeriod': 0, 'totalPwrCsp': 1146165, 'motorPwrCsp': 1006244, 'climatePwrCsp': 99589, 'eDPwrCsp': 39810, 'batteryMgPwrCsp': 522, 'regenPwr': 206645, 'calculativeOdo': 4804}, 
{'drivingPeriod': 1, 'totalPwrCsp': 15282, 'motorPwrCsp': 13416, 'climatePwrCsp': 1327, 'eDPwrCsp': 530, 'batteryMgPwrCsp': 6, 'regenPwr': 2755, 'calculativeOdo': 64.05333333333333}], 

'drivingInfoDetail': [
{'drivingPeriod': 1, 'drivingDate': '202401', 'totalPwrCsp': 414560, 'motorPwrCsp': 365808, 'climatePwrCsp': 35260, 'eDPwrCsp': 12970, 'batteryMgPwrCsp': 522, 'regenPwr': 67603, 'calculativeOdo': 1917}, 
{'drivingPeriod': 1, 'drivingDate': '202312', 'totalPwrCsp': 440831, 'motorPwrCsp': 386261, 'climatePwrCsp': 39290, 'eDPwrCsp': 15280, 'batteryMgPwrCsp': 0, 'regenPwr': 79297, 'calculativeOdo': 1680}, 
{'drivingPeriod': 1, 'drivingDate': '202311', 'totalPwrCsp': 254614, 'motorPwrCsp': 221972, 'climatePwrCsp': 22862, 'eDPwrCsp': 9780, 'batteryMgPwrCsp': 0, 'regenPwr': 49037, 'calculativeOdo': 1028}, 
{'drivingPeriod': 1, 'drivingDate': '202310', 'totalPwrCsp': 36160, 'motorPwrCsp': 32203, 'climatePwrCsp': 2177, 'eDPwrCsp': 1780, 'batteryMgPwrCsp': 0, 'regenPwr': 10708, 'calculativeOdo': 179}]}}

-------------------------------------------------------------------------------------------------------------------

DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_driving_info responseAlltime {'retCode': 'S', 'resCode': '0000', 'resMsg': {'drivingInfo': [
{'drivingPeriod': 0, 'totalPwrCsp': 1125165, 'motorPwrCsp': 987606, 'climatePwrCsp': 98257, 'eDPwrCsp': 38780, 'batteryMgPwrCsp': 522, 'regenPwr': 200131, 'calculativeOdo': 4714}, 
{'drivingPeriod': 1, 'totalPwrCsp': 16073, 'motorPwrCsp': 14108, 'climatePwrCsp': 1403, 'eDPwrCsp': 554, 'batteryMgPwrCsp': 7, 'regenPwr': 2859, 'calculativeOdo': 67.34285714285714}], 

'drivingInfoDetail': [
{'drivingPeriod': 1, 'drivingDate': '202401', 'totalPwrCsp': 414560, 'motorPwrCsp': 365808, 'climatePwrCsp': 35260, 'eDPwrCsp': 12970, 'batteryMgPwrCsp': 522, 'regenPwr': 67603, 'calculativeOdo': 1917}, 
{'drivingPeriod': 1, 'drivingDate': '202312', 'totalPwrCsp': 440831, 'motorPwrCsp': 386261, 'climatePwrCsp': 39290, 'eDPwrCsp': 15280, 'batteryMgPwrCsp': 0, 'regenPwr': 79297, 'calculativeOdo': 1680}, 
{'drivingPeriod': 1, 'drivingDate': '202311', 'totalPwrCsp': 254614, 'motorPwrCsp': 221972, 'climatePwrCsp': 22862, 'eDPwrCsp': 9780, 'batteryMgPwrCsp': 0, 'regenPwr': 49037, 'calculativeOdo': 1028}, 
{'drivingPeriod': 1, 'drivingDate': '202310', 'totalPwrCsp': 15160, 'motorPwrCsp': 13565, 'climatePwrCsp': 845, 'eDPwrCsp': 750, 'batteryMgPwrCsp': 0, 'regenPwr': 4194, 'calculativeOdo': 89}]}}
```

**Comment by cdnninja** [comment]
That log is straight from the Kia server. We have seen reports of this before.   I assume the native app shows the same issue.   If so could open a ticket with Kia if you can catch it in app.

**Comment by WillemD61** [comment]
I now also noticed that the sum of the calculativeOdo readings for period 0 and 1 in the readings above, does not match the odometer reading in the response of get_cached_vehicle_status.

The reading in the get_cached_vehicle_status is correct and matches the app and the car, so this seems to point again in the direction that the response_all_time is not really all_time but just the last 3 months.

To be accurate the naming in the API should be changed to reflect the contents, but is it worth it and does it not affect other users of this API (if they use that naming in further processing) ?

**Comment by WillemD61** [comment]
I am closing this issue.

My observation that the cloud is providing 90 day data and not lifetime cumulative is correct, so after 90 days the old data will disappear (be subtracted) from the totals.

I am now using details of the 30 day data as available in the API to calculate my own lifetime totals.
