### ISSUE TITLE
drvhistory empty for Kona SX2

### ISSUE THREAD

**Issue by jdnn** [Hyundai-Kia-Connect/hyundai_kia_connect_api#557]
-   Hyundai / Kia Connect version: 3.20
-   Python version: 3.9.2
-   Operating System: Debian bullseye

### Description

Running monitor.py  from hyundai_kia_connect_monitor gives me an empty drvhistory, as in:

DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_driving_info response30d {'retCode': 'S', 'resCode': '0000', 'resMsg': {'drivingInfo': [{'drivingPeriod': 0}, {'drivingPeriod': 1}, {'drivingPeriod': 2}], 'drivingInfoDetail': []}, ...

### What I Did

Another user told me that its working with v3.17.5, and in fact, the same monitor.py run with v3.17.5 on the same Kona results in a populated drivingInfoDetail.

I checked the drvhistory queries using the two versions. URL and body are identical, but the headers aren't. In particular, v3.17.5 has 'Ccuccs2protocolsupport': '1', while v3.20 does the query with value '0'. And in fact, hardcoding that to value '1' in v3.20 gives the same data for drivingInfoDetail as with v3.17.5.

So the question, does ccs2_support need to be configured manually, or is there an issue to be fixed in v3.20?

**Comment by cdnninja** [comment]
This sounds like a bug.

**Comment by ZuinigeRijder** [comment]
@cdnninja Probably this because of the following change:

`hyundai_kia_connect_api-3.17.4\hyundai_kia_connect_api\KiaUvoApiEU.py:239:            "Ccuccs2protocolsupport": self.ccu_ccs2_protocol_support,`

`hyundai_kia_connect_api-3.20.0\hyundai_kia_connect_api\ApiImplType1.py:41:            "Ccuccs2protocolsupport": str(ccs2_support or 0),`

**Comment by cdnninja** [comment]
That is passed in correctly however looking at the calling files it isn't always passed into the method.  Off the side of my desk I drafted a PR with a find replace but clearly needs more work.

**Comment by cdnninja** [comment]
Could you review #558 and let me know thoughts?

**Comment by ZuinigeRijder** [comment]
I looked at the changes and they seem ok. I did run with this PR version and my dailystats for the IONIQ5 is retrieved without errors. Because I do not have a newer Kona or ccNC car, probably @jdnn could test if this the problem (before or after the pull request).

**Comment by jdnn** [comment]
I replaced the KiaUvoApiEU.py with the #558 file and ran monitor.py against my Kona. Works fine now, the drvhistory / dailystats are fetched without errors.  Thanks for the quick fix.

**Comment by cdnninja** [comment]
Merged and released.  Thanks all.
