### ISSUE TITLE
Not an issue but more of a request 

### ISSUE THREAD

**Issue by DarkSlice1** [Hyundai-Kia-Connect/hyundai_kia_connect_api#56]
I'm trying to intergrade the call flow into my application but can't get it working with postman. You don't happen to have something like that lying around? 🙂

**Comment by cdnninja** [comment]
What country and brand are you trying to connect to?  I don't have anything specific but I can point you in the right direction to review our code I would think.

**Comment by DarkSlice1** [comment]
Ireland, Kia 🙂

**Comment by cdnninja** [comment]
What language are you working in? I would encourage you to use an existing library if you can.  Europe is the most complicated call flow.  I don't know the europe side as well as the others. 

You need to incorporate this repo as Kia rotates the stamps all the time: https://github.com/neoPix/bluelinky-stamps

This file is the flow on how to call kia europe: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/KiaUvoApiEU.py

Specifically the login method is the bet place start: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/52321286324b57fe3d5aca36ab18c9d72082f0d4/hyundai_kia_connect_api/KiaUvoApiEU.py#L98-L125
