### ISSUE TITLE
Update cars soc status.

### ISSUE THREAD

**Issue by TraipZe** [Hyundai-Kia-Connect/hyundai_kia_connect_api#598]
-   Kia Connect version: 2.1.20
- 
-   Python version:
-   Operating System: SG2AE.S5BLC.AEU

### Description
Trying to Update soc sensor for home assist to automatically control charge.
But it’s not updating when I charge.

Installed Kia uvo hacs integration and connected to my car.
Set update to lowest 15min but not even after update, if it’s even doing the update the charge sensor does not update.

### What I Did

Tried to refresh integration,  no luck, how can I get it to update?

**Comment by cdnninja** [comment]
What does the native app show?
