### ISSUE TITLE
v3.22.4 release GitHub action to PyPi failed, preventing HA integration from loading

### ISSUE THREAD

**Issue by Snuffy2** [Hyundai-Kia-Connect/hyundai_kia_connect_api#612]
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/actions/runs/10413425695/job/28840798290

This is preventing the latest HA integration from loading. 
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/921

**Comment by cdnninja** [comment]
Should be good now.
