### ISSUE TITLE
status.airTemp.value issue for Canadian Genesis connection

### ISSUE THREAD

**Issue by navdeepd** [Hyundai-Kia-Connect/hyundai_kia_connect_api#649]
-   Hyundai / Kia Connect version: Any version beyond 2.26.6
-   Python version: 3.12.4
-   Operating System:  ghcr.io/home-assistant/home-assistant:stable container

### Description

After  merge #625 I have been receiving the following error on my Canadian Genesis, reverting to 3.23.0 of hyundai_kia_connect_api stops this error from occurring.

  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 180, in update_vehicle_with_cached_state
    self._update_vehicle_properties_base(vehicle, state)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 252, in _update_vehicle_properties_base
    and get_child_value(state, "status.airTemp.value")[-1] == "H"
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable

### What I Did

Simple start of home assistant plugin kia_uvo. This issue occurs persistently after updating from 2.26.6 of the connect plugin for home assistant. I have performed a local workaround by simply updating the check to include a check for None type however I am not sure if this would negatively impact anything else further in the code.

i.e.
```
        if (
            get_child_value(state, "status.airTemp.value") is not None
            and get_child_value(state, "status.airTemp.value") != "OFF"
            and get_child_value(state, "status.airTemp.value")[-1] == "H"
        ):
```

**Comment by cdnninja** [comment]
I added the check. That should solve it.   

Could you update your manifest file and test for me?

**Comment by navdeepd** [comment]
Thanks, works fine for me.
