### ISSUE TITLE
odometer not updating during driving, while location and SOC is updating.

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#65]
* Hyundai / Kia Connect version: hyundai_kia_connect_api-1.34.2
* Python version: Python 3.9.13
* Operating System: Raspberry Pi Bulls Eye and Windows 10

### Description

I made Automatic trip administration tools for Hyundai Bluelink or Kia UVO Connect users, using hyundai_kia_connect_api-1.34.2, 
named [hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor)

I noticed that odometer is not updated, while locations and SOC is updated while driving.  

- Is this a problem in hyundai_kia_connect_api-1.34.2?
- Or is this a problem in the bluelink API functionality, that it will update this only when shutting the car down?

Example output [monitor.py](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/blob/main/monitor.py)
````
datetime, longitude, latitude, engineOn, 12V%, odometer, SOC%, charging, plugged
2022-09-24 11:00:49+02:00, 5.129967, 51.674819, True, 92, 17390.8, 98, False, 0
2022-09-24 11:30:38+02:00, 5.204728, 51.883719, True, 97, 17390.8, 91, False, 0
2022-09-24 12:00:44+02:00, 5.250064, 52.256122, True, 98, 17390.8, 81, False, 0
2022-09-24 12:30:39+02:00, 5.540714, 52.575733, True, 98, 17390.8, 69, False, 0
2022-09-24 13:00:39+02:00, 5.768325, 52.898894, True, 98, 17390.8, 57, False, 0
````
The odometer keeps 17390.8, while location and SOC is updated when polling each half hour.

I use region = 1 (REGION_EUROPE) and brand = 2 (BRAND_HYUNDAI) and call:
````
manager.check_and_refresh_token()
manager.check_and_force_update_vehicles(600)
````

Indirectly KiaUvoApiEU.py is used then.

### What I Did

Tried to use manager.force_refresh_all_vehicles_states(), but same result, odometer seems to be updated after turning the car off?

```
            manager = VehicleManager(
                region=int(REGION),
                brand=int(BRAND),
                username=USERNAME,
                password=PASSWORD,
                pin=PIN
            )
            manager.check_and_refresh_token()
            manager.force_refresh_all_vehicles_states()
```

**Comment by ZuinigeRijder** [comment]
I have other data, which shows that, as long the car is not shut off, the odometer will not update.

````
datetime, longitude, latitude, engineOn, 12V%, odometer, SOC%, charging, plugged
2022-09-27 14:30:44+02:00, 5.124957, 51.68260, False, 92, 17846.9, 50, False, 0
2022-09-27 15:00:33+02:00, 5.139075, 51.683042, True, 88, 17846.9, 49, False, 0
2022-09-27 15:30:39+02:00, 5.135244, 51.692155, True, 94, 17846.9, 49, False, 0
2022-09-27 16:00:55+02:00, 5.124957, 51.68260, False, 95, 17853.4, 48, False, 0
````

I started my trip around 14:50, stopped around 15:05 (car in Park), driven again a short distance, again car in park around 15:15. Arrived at home around 15:45. You see above, that the odometer is updated at 16:00. So it looks like it is updated only when the car was shut off.

That also suggest, this is not because of hyundai_kia_connect_api API implementation, but because of the behavior of bluelink.

**Comment by cdnninja** [comment]
The API itself has a few unique items like this.  I believe odometer checks in after the car is off.

**Comment by ZuinigeRijder** [comment]
Because it is part of the bluelink API, I close this issue.
