### ISSUE TITLE
from hyundai_kia_connect_api import *  results in  TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by kw123** [Hyundai-Kia-Connect/hyundai_kia_connect_api#66]
* Hyundai / Kia Connect version:
* Python version:
* Operating System:

### Description
getting error in first line of example
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
first line  in example:
from hyundai_kia_connect_api import *

### What I Did
```
python3 
from hyundai_kia_connect_api import *
```

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```from hyundai_kia_connect_api import *
```
result:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/kia/hyundai_kia_connect_api/hyundai_kia_connect_api/__init__.py", line 3, in <module>
    from .ApiImpl import ApiImpl, ClimateRequestOptions
  File "/home/pi/kia/hyundai_kia_connect_api/hyundai_kia_connect_api/ApiImpl.py", line 27, in <module>
    class ApiImpl:
  File "/home/pi/kia/hyundai_kia_connect_api/hyundai_kia_connect_api/ApiImpl.py", line 38, in ApiImpl
    def get_vehicles(self, token: Token) -> list[Vehicle]:
TypeError: 'type' object is not subscriptable
```

**Comment by kw123** [comment]
ps:  python version: 3.7.3

**Comment by cdnninja** [comment]
Try from hyundai_kia_connect_api.VehicleManager import VehicleManager

**Comment by kw123** [comment]
same error message

**Comment by cdnninja** [comment]
Could you try python 3.9?

**Comment by kw123** [comment]
tried w python 3.10: got a little further 
VehicleManager.py", line 51, in initialize
    self.token.pin = self.pin
AttributeError: 'NoneType' object has no attribute 'pin'
(line number is different I added some print statements before )

**Comment by kw123** [comment]
```import os, sys

from hyundai_kia_connect_api.VehicleManager import VehicleManager


def test_EU_login():
    username = "xxx"
    password = "xxx"
    pin = ""
    vm = VehicleManager(
        region=1, brand=1, username=username, password=password, pin=pin
    )
    vm.check_and_refresh_token()
    assert len(vm.vehicles.keys()) > 0

test_EU_login()


traceback

python3 eu_login_test.py
Traceback (most recent call last):
  File "/Users/karlwachs/kia/eu_login_test.py", line 16, in <module>
    test_EU_login()
  File "/Users/karlwachs/kia/eu_login_test.py", line 13, in test_EU_login
    vm.check_and_refresh_token()
  File "/Users/karlwachs/kia/hyundai_kia_connect_api/VehicleManager.py", line 88, in check_and_refresh_token
    self.initialize()
  File "/Users/karlwachs/kia/hyundai_kia_connect_api/VehicleManager.py", line 47, in initialize
    self.token.pin = self.pin
AttributeError: 'NoneType' object has no attribute 'pin'
```

with userid and password xxx-ed

**Comment by kw123** [comment]
* w python 3.10

**Comment by cdnninja** [comment]
I do think something is up on the build that may be related. Could you try an older version in the meantime? I hope to dig in tomorrow.

**Comment by cdnninja** [comment]
The issue I saw wasn't related. I just confirming our code is passing the above in our github action tests.

**Comment by cdnninja** [comment]
What version of this library are you using?

**Comment by cdnninja** [comment]
Any update on this?

**Comment by zulufoxtrot** [comment]
I'm having the exact same error.
Version 1.34.7 from PyPi. Python 3.8

**Comment by cdnninja** [comment]
> 

3.8 isn't supported.  Please try 3.9 or newer.

**Comment by zulufoxtrot** [comment]
Oops. Totally missed that.
Upgraded project to 3.9. This specific error appears to be gone and was probably indeed related to python version.
I'm getting a different error now, I'll open a separate issue.
