### ISSUE TITLE
from locale import D_T_FMT

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#80]
* Hyundai / Kia Connect version: 1.34.2
* Python version: 3.9.13
* Operating System: Windows 10

### Description

The following import gives an error while interpreting:

hyundai_kia_connect_api\HyundaiBlueLinkAPIUSA.py:1:from locale import D_T_FMT

C:\Users\Rick\git\monitor>python monitor.py
Traceback (most recent call last):
  File "C:\Users\Rick\git\monitor\monitor.py", line 38, in <module>
    from hyundai_kia_connect_api import VehicleManager
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\__init__.py", line 4, in <module>
    from .HyundaiBlueLinkAPIUSA import HyundaiBlueLinkAPIUSA
  **File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\HyundaiBlueLinkAPIUSA.py", line 1, in <module>
    from locale import D_T_FMT**
ImportError: cannot import name 'D_T_FMT' from 'locale' (C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\locale.py)

### What I Did

If I comment the line (it is not used in the source code!), everything runs fine.
What package should have been installed to have this **"from locale import D_T_FMT working"**?
What was the intention of this import statement?

### Research
Appears that this D_T_FMT is not available on Windows according to this question:
https://stackoverflow.com/questions/14103365/python-elegant-bypass-to-not-having-locale-d-t-fmt-on-windows

Because it is NOT used, removing the import statement would be the solution I guess.

**Comment by cdnninja** [comment]
Good catch.  I have created a PR to fix this.  Thanks for this.  Many regions were written by others and copy pasted since I don't have cars in these regions. Any PRs are appreciated as this region doesn't have an owner.
