### ISSUE TITLE
pypi Doesn't Auto Run

### ISSUE THREAD

**Issue by cdnninja** [Hyundai-Kia-Connect/hyundai_kia_connect_api#9]
Looks like the release trigger doesn't work for pypi which can make it out of sync with this repo.

**Comment by fuatakgun** [comment]
I could not make it work, any suggestions? I was mostly working it manually :-)

**Comment by cdnninja** [comment]
Resolved.   I merged it back into a single config flow so we didn't need to use tokens.  Just added if statements so it won't run if a release isn't created.
